plugins {
    id 'java'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(22)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':')
    implementation 'io.netty:netty-buffer:4.1.100.Final'
}

jar {
    enabled = false
}

tasks.register('printRuntimeClasspath') {
    doLast {
        println sourceSets.main.runtimeClasspath.asPath
    }
}
