<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>12.0</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <ProjectReference Include="../../../samples/Bingo/Server/Configuration/Bingo.Server.Configuration.csproj" />
    <ProjectReference Include="../../../samples/Bingo/Server/Api/Bingo.Server.Api.csproj" />
    <ProjectReference Include="../../../samples/Bingo/Server/Play/Bingo.Server.Play.csproj" />
    <ProjectReference Include="../../../samples/Bingo/Server/Session/Bingo.Server.Session.csproj" />
    <ProjectReference Include="../../../src/Zlink.Framework/Zlink.Framework.csproj" />
    <ProjectReference Include="../../../src/Zlink.Framework.AspNetCore/Zlink.Framework.AspNetCore.csproj" />
  </ItemGroup>
</Project>
