/* SPDX-License-Identifier: MPL-2.0 */

#ifndef __ZLINK_LEGACY_API_INTERNAL_HPP_INCLUDED__
#define __ZLINK_LEGACY_API_INTERNAL_HPP_INCLUDED__

typedef enum zlink_gateway_option_t
{
    ZLINK_GATEWAY_OPT_SNDHWM = 0x2101,
    ZLINK_GATEWAY_OPT_RCVHWM = 0x2102,
    ZLINK_GATEWAY_OPT_SNDTIMEO = 0x2103,
    ZLINK_GATEWAY_OPT_LINGER = 0x2104,
    ZLINK_GATEWAY_OPT_SNDBUF = 0x2105,
    ZLINK_GATEWAY_OPT_RCVBUF = 0x2106
} zlink_gateway_option_t;

#endif
