# SPDX-License-Identifier: MPL-2.0

from ._core import (
    Context,
    ContextOptions,
    Message,
    Received,
    Subscribed,
    TopicMessage,
    RoutingId,
    SubscriptionEvent,
    ZlinkError,
    MSG_TYPE_DATA,
    MSG_TYPE_REQUEST,
    MSG_TYPE_REPLY,
    METADATA_KEY_USER_MIN,
    METADATA_VALUE_MAX,
)
from ._ffi import lib as _lib
from ._socket_base import (
    CommonSocketOptions,
    DealerSocketOptions,
    StreamSocketOptions,
    SubSocketOptions,
)
from ._socket_types import (
    DealerSocket,
    PairSocket,
    PubSocketOptions,
    PubSocket,
    RouterSocketOptions,
    RouterSocket,
    StreamSocket,
    SubSocket,
    XPubSocket,
    XSubSocket,
)
from ._request_reply import RequestDealer, RequestRouter
from ._poller import Poller
from ._monitor import (
    MonitorSnapshot,
    MonitorSocket,
    ServiceEvent,
    ServiceMonitor,
    ServiceMonitorEvent,
    SocketMonitorEvent,
)
from ._discovery import (
    Discovery,
    MemberPeerEntry,
    Registry,
    RegistryQueryClient,
    RegistryServiceSummaryEntry,
    RegistryServiceSummaryFilter,
    RegistryStatus,
    RegistryTopologyEntry,
    RegistryTopologyFilter,
)
from ._spot import (
    SpotNode,
    Spot,
    SpotNodeStatus,
    SpotNodePeerEntry,
    SpotNodePeerFilter,
    SpotNodeSubjectEntry,
    SpotNodeSubjectFilter,
)
from ._enums import (
    SocketType,
    ContextOption,
    SocketOption,
    RouterOption,
    SendResult,
    ErrorCode,
    ProtocolError,
    MonitorEvent,
    DisconnectReason,
    PollEvent,
    RegistryState,
    ServiceType,
    ServiceRole,
    ServiceMonitorMask,
    TopologySource,
    TopologyState,
    RegistrySocketRole,
    DiscoverySocketRole,
    SpotNodeSocketRole,
    SpotNodeOption,
    SpotNodePubMode,
    SpotNodePubQueueFullPolicy,
    SpotNodeState,
    SpotPeerSource,
    SpotPeerState,
    SpotSocketRole,
)

SERVICE_TYPE_SPOT = ServiceType.SPOT


def version():
    import ctypes

    L = _lib()
    major = ctypes.c_int()
    minor = ctypes.c_int()
    patch = ctypes.c_int()
    L.zlink_version(ctypes.byref(major), ctypes.byref(minor), ctypes.byref(patch))
    return major.value, minor.value, patch.value


__all__ = [
    "version",
    "Context",
    "ContextOptions",
    "CommonSocketOptions",
    "DealerSocketOptions",
    "StreamSocketOptions",
    "SubSocketOptions",
    "PubSocketOptions",
    "RouterSocketOptions",
    "PairSocket",
    "DealerSocket",
    "RouterSocket",
    "StreamSocket",
    "PubSocket",
    "SubSocket",
    "XPubSocket",
    "XSubSocket",
    "RequestDealer",
    "RequestRouter",
    "Message",
    "Received",
    "Subscribed",
    "TopicMessage",
    "RoutingId",
    "SubscriptionEvent",
    "Poller",
    "MonitorSnapshot",
    "MonitorSocket",
    "ServiceMonitor",
    "ServiceEvent",
    "SocketMonitorEvent",
    "ServiceMonitorEvent",
    "Registry",
    "Discovery",
    "MemberPeerEntry",
    "RegistryStatus",
    "RegistryServiceSummaryEntry",
    "RegistryServiceSummaryFilter",
    "RegistryTopologyEntry",
    "RegistryTopologyFilter",
    "RegistryQueryClient",
    "SERVICE_TYPE_SPOT",
    "SpotNode",
    "Spot",
    "SpotNodeStatus",
    "SpotNodePeerEntry",
    "SpotNodePeerFilter",
    "SpotNodeSubjectEntry",
    "SpotNodeSubjectFilter",
    "ZlinkError",
    "SocketType",
    "ContextOption",
    "SocketOption",
    "RouterOption",
    "SendResult",
    "ErrorCode",
    "ProtocolError",
    "MonitorEvent",
    "DisconnectReason",
    "PollEvent",
    "RegistryState",
    "ServiceType",
    "ServiceRole",
    "ServiceMonitorMask",
    "TopologySource",
    "TopologyState",
    "RegistrySocketRole",
    "DiscoverySocketRole",
    "SpotNodeSocketRole",
    "SpotNodeOption",
    "SpotNodePubMode",
    "SpotNodePubQueueFullPolicy",
    "SpotNodeState",
    "SpotPeerSource",
    "SpotPeerState",
    "SpotSocketRole",
]
