# SPDX-License-Identifier: MPL-2.0

from .contracts import *  # noqa: F401,F403

for _legacy_name in ("SendResult", "SendFlag", "ReceiveFlag"):
    globals().pop(_legacy_name, None)
del _legacy_name

AUTO_CONNECT_ROUTE_MESH = AutoConnectType.ROUTE_MESH
AUTO_CONNECT_CLIENT_SERVER = AutoConnectType.CLIENT_SERVER
AUTO_CONNECT_DEALER_MESH = AutoConnectType.DEALER_MESH
AUTO_CONNECT_FANOUT = AutoConnectType.FANOUT
AUTO_CONNECT_SPOT_MESH = AutoConnectType.SPOT_MESH


__all__ = [
    "version",
    "strerror",
    "has",
    "proxy",
    "proxy_steerable",
    "sleep",
    "multipart_close",
    "Context",
    "ContextOptions",
    "CommonSocketOptions",
    "DealerSocketOptions",
    "StreamSocketOptions",
    "SubSocketOptions",
    "PubSocketOptions",
    "RouterSocketOptions",
    "PairSocket",
    "DealerSocket",
    "RouterSocket",
    "StreamSocket",
    "PubSocket",
    "SubSocket",
    "XPubSocket",
    "XSubSocket",
    "Message",
    "Received",
    "Subscribed",
    "TopicMessage",
    "RoutingId",
    "SubscriptionEvent",
    "AtomicCounter",
    "Stopwatch",
    "Thread",
    "Timer",
    "Poller",
    "MonitorSnapshot",
    "MonitorEvent",
    "MonitorSocket",
    "SocketMonitorEvent",
    "Registry",
    "Discovery",
    "MemberPeerEntry",
    "RegistryStatus",
    "RegistryServiceSummaryEntry",
    "RegistryServiceSummaryFilter",
    "RegistryTopologyEntry",
    "RegistryTopologyFilter",
    "RegistryQueryClient",
    "AUTO_CONNECT_ROUTE_MESH",
    "AUTO_CONNECT_CLIENT_SERVER",
    "AUTO_CONNECT_DEALER_MESH",
    "AUTO_CONNECT_FANOUT",
    "AUTO_CONNECT_SPOT_MESH",
    "SendOp",
    "RequestOp",
    "RequestCallbackOp",
    "ReplyOp",
    "SpotNode",
    "Spot",
    "Actor",
    "ActorRef",
    "ActorJoinRequest",
    "ActorRoute",
    "ActorRecvInfo",
    "ActorJoinInfo",
    "ActorPart",
    "remote_actor_ref",
    "SpotDispatchInfo",
    "SpotNodeActorEntry",
    "SpotNodeSpotEntry",
    "SpotNodeStatus",
    "SpotNodePeerEntry",
    "SpotNodePeerFilter",
    "SpotNodeSubjectEntry",
    "SpotNodeSubjectFilter",
    "SpotNodeSocketSnapshotEntry",
    "SpotNodeSocketSnapshotFilter",
    "ZlinkError",
    "SubmitError",
    "RequestError",
    "RecvError",
    "HandlerError",
    "CloseError",
    "BindError",
    "ConnectError",
    "ConfigError",
    "SocketType",
    "ContextOption",
    "AutoHwmProfile",
    "SocketOption",
    "RouterOption",
    "SendFlags",
    "RecvFlags",
    "SubmitResult",
    "RequestResult",
    "RecvResult",
    "HandlerResult",
    "CloseResult",
    "BindResult",
    "ConnectResult",
    "ConfigResult",
    "ErrorCode",
    "ProtocolError",
    "MonitorEventMask",
    "DisconnectReason",
    "PollEvent",
    "PollEventFlag",
    "RidDuplicatePolicy",
    "RegistryState",
    "AutoConnectType",
    "ServiceRole",
    "TopologySource",
    "TopologyState",
    "RegistrySocketRole",
    "DiscoverySocketRole",
    "SpotNodeSocketRole",
    "SpotNodeMode",
    "SpotNodeSocketOwner",
    "SpotNodeOption",
    "SpotNodeState",
    "SpotPeerSource",
    "SpotPeerState",
    "SpotDispatchEvent",
    "SpotDispatchSubjectKind",
    "SpotSocketRole",
    "SpotServiceAttachmentRole",
    "ServiceKind",
    "SubjectKind",
    "SpotRole",
    "PollSourceKind",
    "PollerEvent",
]
