package dev.kairoscode.zlink.integration;

import dev.kairoscode.zlink.Context;
import dev.kairoscode.zlink.SendFlag;
import dev.kairoscode.zlink.Socket;
import dev.kairoscode.zlink.SocketOption;
import dev.kairoscode.zlink.SocketType;
import dev.kairoscode.zlink.TestSupport;
import org.junit.jupiter.api.Test;

import java.nio.charset.StandardCharsets;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class TestRouterAutoIdFormatPortedTest {
    @Test
    public void testRouterReceivesAutoGeneratedDealerIdWithLength16() {
        TestSupport.assumeNative();

        try (Context ctx = new Context();
             Socket router = new Socket(ctx, SocketType.ROUTER);
             Socket dealer = new Socket(ctx, SocketType.DEALER)) {
            router.setSockOpt(SocketOption.LINGER, 0);
            dealer.setSockOpt(SocketOption.LINGER, 0);

            String endpoint = TestSupport.tcpEndpoint();
            router.bind(endpoint);
            dealer.connect(endpoint);

            dealer.send("hello".getBytes(StandardCharsets.UTF_8), SendFlag.NONE);

            byte[] rid = TestSupport.recvWithTimeout(router, 255,
                TestSupport.DEFAULT_TIMEOUT_MS);
            assertEquals(16, rid.length);

            byte[] payload = TestSupport.recvWithTimeout(router, 64,
                TestSupport.DEFAULT_TIMEOUT_MS);
            assertEquals("hello", new String(payload, StandardCharsets.UTF_8));
        }
    }
}
