<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>SpotService.Client</AssemblyName>
    <RootNamespace>SpotService.Client</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/Zlink.HttpClient/Zlink.HttpClient.csproj" />
  </ItemGroup>
</Project>
