/* SPDX-License-Identifier: MPL-2.0 */

#ifndef __ZLINK_ENUM_H_INCLUDED__
#define __ZLINK_ENUM_H_INCLUDED__

#include <stdint.h>

typedef enum zlink_ctx_option_t
{
    ZLINK_IO_THREADS = 1,
    ZLINK_MAX_SOCKETS = 2,
    ZLINK_SOCKET_LIMIT = 3,
    ZLINK_THREAD_PRIORITY = 3,
    ZLINK_THREAD_SCHED_POLICY = 4,
    ZLINK_MAX_MSGSZ = 5,
    ZLINK_MSG_T_SIZE = 6,
    ZLINK_THREAD_AFFINITY_CPU_ADD = 7,
    ZLINK_THREAD_AFFINITY_CPU_REMOVE = 8,
    ZLINK_THREAD_NAME_PREFIX = 9,
    ZLINK_CTX_OPT_BLOCKY = 10,
    ZLINK_CTX_OPT_AUTO_HWM_ENABLE = 12,
    ZLINK_CTX_OPT_AUTO_HWM_RECALC_DEBOUNCE_MS = 14,
    ZLINK_CTX_OPT_AUTO_HWM_PROFILE = 17
} zlink_ctx_option_t;

typedef enum zlink_auto_hwm_profile_t
{
    ZLINK_AUTO_HWM_PROFILE_COMPACT = 0,
    ZLINK_AUTO_HWM_PROFILE_LOW_LATENCY = 1,
    ZLINK_AUTO_HWM_PROFILE_BALANCED = 2,
    ZLINK_AUTO_HWM_PROFILE_THROUGHPUT = 3
} zlink_auto_hwm_profile_t;

typedef enum zlink_socket_type_t
{
    ZLINK_SOCKET_ANY = 0,
    ZLINK_SOCKET_PAIR = 0x1001,
    ZLINK_SOCKET_PUB = 0x1002,
    ZLINK_SOCKET_SUB = 0x1003,
    ZLINK_SOCKET_DEALER = 0x1004,
    ZLINK_SOCKET_ROUTER = 0x1005,
    ZLINK_SOCKET_XPUB = 0x1006,
    ZLINK_SOCKET_XSUB = 0x1007,
    ZLINK_SOCKET_STREAM = 0x1008
} zlink_socket_type_t;

typedef enum zlink_spot_node_mode_t
{
    ZLINK_SPOT_NODE_MODE_PUBSUB = 1,
    ZLINK_SPOT_NODE_MODE_ROUTED = 2,
    ZLINK_SPOT_NODE_MODE_ALL = 3
} zlink_spot_node_mode_t;

typedef enum zlink_spot_node_socket_owner_t
{
    ZLINK_SPOT_NODE_SOCKET_OWNER_ANY = 0,
    ZLINK_SPOT_NODE_SOCKET_OWNER_NODE = 1,
    ZLINK_SPOT_NODE_SOCKET_OWNER_SPOT = 2
} zlink_spot_node_socket_owner_t;

typedef enum zlink_option_t
{
    /* Queue, buffer, and message size options */
    ZLINK_OPT_AFFINITY = 0x3001,
    ZLINK_OPT_RATE = 0x3003,
    ZLINK_OPT_RECOVERY_IVL = 0x3004,
    ZLINK_OPT_SNDBUF = 0x3005,
    ZLINK_OPT_RCVBUF = 0x3006,
    ZLINK_OPT_MAXMSGSIZE = 0x300E,
    ZLINK_OPT_SNDHWM = 0x300F,
    ZLINK_OPT_RCVHWM = 0x3010,

    /* Lifecycle, timeout, and reconnect options */
    ZLINK_OPT_LINGER = 0x300A,
    ZLINK_OPT_RECONNECT_IVL = 0x300B,
    ZLINK_OPT_BACKLOG = 0x300C,
    ZLINK_OPT_RECONNECT_IVL_MAX = 0x300D,
    ZLINK_OPT_MULTICAST_HOPS = 0x3011,
    ZLINK_OPT_RCVTIMEO = 0x3012,
    ZLINK_OPT_SNDTIMEO = 0x3013,
    ZLINK_OPT_CONNECT_TIMEOUT = 0x3024,
    ZLINK_OPT_HANDSHAKE_IVL = 0x301D,

    /* TCP keepalive and transport-level TCP options */
    ZLINK_OPT_TCP_KEEPALIVE = 0x3015,
    ZLINK_OPT_TCP_KEEPALIVE_CNT = 0x3016,
    ZLINK_OPT_TCP_KEEPALIVE_IDLE = 0x3017,
    ZLINK_OPT_TCP_KEEPALIVE_INTVL = 0x3018,
    ZLINK_OPT_TCP_MAXRT = 0x3025,
    ZLINK_OPT_TCP_NODELAY = 0x3031,

    /* Heartbeat options */
    ZLINK_OPT_HEARTBEAT_IVL = 0x3021,
    ZLINK_OPT_HEARTBEAT_TTL = 0x3022,
    ZLINK_OPT_HEARTBEAT_TIMEOUT = 0x3023,

    /* Network and address-family options */
    ZLINK_OPT_IPV6 = 0x301A,
    ZLINK_OPT_TOS = 0x301C,
    ZLINK_OPT_MULTICAST_MAXTPDU = 0x3026,
    ZLINK_OPT_BINDTODEVICE = 0x3027,
    ZLINK_OPT_TLS_CERT = 0x3028,
    ZLINK_OPT_TLS_KEY = 0x3029,
    ZLINK_OPT_TLS_CA = 0x302A,
    ZLINK_OPT_TLS_VERIFY = 0x302B,
    ZLINK_OPT_TLS_REQUIRE_CLIENT_CERT = 0x302C,
    ZLINK_OPT_TLS_HOSTNAME = 0x302D,
    ZLINK_OPT_TLS_TRUST_SYSTEM = 0x302E,
    ZLINK_OPT_TLS_PASSWORD = 0x302F,

    /* Delivery, buffering policy, and filter semantics */
    ZLINK_OPT_IMMEDIATE = 0x3019,
    ZLINK_OPT_CONFLATE = 0x301B,
    ZLINK_OPT_BLOCKY = 0x301E,
    ZLINK_OPT_INVERT_MATCHING = 0x3020,

    /* Introspection and protocol metadata */
    ZLINK_OPT_FD = 0x3007,
    ZLINK_OPT_EVENTS = 0x3008,
    ZLINK_OPT_TYPE = 0x3009,
    ZLINK_OPT_LAST_ENDPOINT = 0x3014,
    ZLINK_OPT_ZMP_METADATA = 0x3030,
    ZLINK_OPT_ROUTE_VALUE_MAX_SIZE = 0x3032,
    ZLINK_OPT_RID_DUPLICATE_POLICY = 0x3033,
    ZLINK_OPT_AUTO_HWM_MSG_UNIT_BYTES = 0x3034,
    ZLINK_OPT_DISCOVERY_SPOT_OWNER_SYNC = 0x3035,
    ZLINK_OPT_DISCOVERY_ACTOR_ROUTE_SYNC = 0x3036
} zlink_option_t;

typedef enum zlink_rid_duplicate_policy_t
{
    ZLINK_RID_DUPLICATE_REJECT = 0,
    ZLINK_RID_DUPLICATE_HANDOVER = 1
} zlink_rid_duplicate_policy_t;

typedef enum zlink_router_option_t
{
    ZLINK_ROUTER_OPT_MANDATORY = 0x3101,
    ZLINK_ROUTER_OPT_PROBE = 0x3103,
    ZLINK_ROUTER_OPT_CONNECT_ROUTING_ID = 0x3104,
    ZLINK_ROUTER_OPT_REQUEST_TIMEOUT_MS = 0x3105,
    ZLINK_ROUTER_OPT_WEIGHT = 0x3106
} zlink_router_option_t;

typedef enum zlink_dealer_option_t
{
    ZLINK_DEALER_OPT_PROBE = 0x3201,
    ZLINK_DEALER_OPT_REQUEST_TIMEOUT_MS = 0x3202,
    ZLINK_DEALER_OPT_WEIGHT = 0x3203
} zlink_dealer_option_t;

typedef enum zlink_pub_option_t
{
    ZLINK_PUB_OPT_VERBOSE = 0x3301,
    ZLINK_PUB_OPT_VERBOSER = 0x3302,
    ZLINK_PUB_OPT_MANUAL = 0x3303,
    ZLINK_PUB_OPT_MANUAL_LAST_VALUE = 0x3304,
    ZLINK_PUB_OPT_NODROP = 0x3305,
    ZLINK_PUB_OPT_WELCOME_MSG = 0x3306,
    ZLINK_PUB_OPT_TOPICS_COUNT = 0x3307,
    ZLINK_PUB_OPT_APPROVE_SUBSCRIBE = 0x3308,
    ZLINK_PUB_OPT_REJECT_SUBSCRIBE = 0x3309
} zlink_pub_option_t;

typedef enum zlink_sub_option_t
{
    ZLINK_SUB_OPT_TOPICS_COUNT = 0x3400
} zlink_sub_option_t;

typedef enum zlink_stream_option_t
{
    ZLINK_STREAM_OPT_NOTIFY = 0x3501
} zlink_stream_option_t;

typedef enum zlink_spot_node_option_t
{
    /* 0x3608..0x360D are reserved for removed direction-based HWM and queue
       hard-limit options. Do not reuse them for new public meanings. */
    ZLINK_SPOT_NODE_OPT_ROUTER_HWM_PROFILE = 0x360E,
    ZLINK_SPOT_NODE_OPT_ROUTER_HWM = 0x360F,
    ZLINK_SPOT_NODE_OPT_PUBSUB_HWM_PROFILE = 0x3610,
    ZLINK_SPOT_NODE_OPT_PUBSUB_HWM = 0x3611,
    ZLINK_SPOT_NODE_OPT_DISPATCH_WORKERS_MIN = 0x3612,
    ZLINK_SPOT_NODE_OPT_DISPATCH_WORKERS_MAX = 0x3613
} zlink_spot_node_option_t;

typedef enum zlink_spot_option_t
{
    ZLINK_SPOT_OPT_REQUEST_TIMEOUT_MS = 0x3701
} zlink_spot_option_t;

typedef enum zlink_registry_option_t
{
    ZLINK_REGISTRY_OPT_ID = 0x3801,
    ZLINK_REGISTRY_OPT_HEARTBEAT_INTERVAL_MS = 0x3802,
    ZLINK_REGISTRY_OPT_HEARTBEAT_TIMEOUT_MS = 0x3803,
    ZLINK_REGISTRY_OPT_BROADCAST_INTERVAL_MS = 0x3804
} zlink_registry_option_t;

typedef enum zlink_disconnect_reason_t
{
    ZLINK_DISCONNECT_REASON_UNKNOWN = 0,
    ZLINK_DISCONNECT_REASON_HANDSHAKE_FAILED = 3,
    ZLINK_DISCONNECT_REASON_TRANSPORT_ERROR = 4,
    ZLINK_DISCONNECT_REASON_CTX_TERM = 5
} zlink_disconnect_reason_t;

typedef enum zlink_auto_hwm_recalc_reason_t
{
    ZLINK_AUTO_HWM_RECALC_REASON_NONE = 0,
    ZLINK_AUTO_HWM_RECALC_REASON_INITIAL = 1,
    ZLINK_AUTO_HWM_RECALC_REASON_ROLE_CHANGE = 2,
    ZLINK_AUTO_HWM_RECALC_REASON_POLICY_TOGGLE = 3,
    ZLINK_AUTO_HWM_RECALC_REASON_REFRESH = 4,
    ZLINK_AUTO_HWM_RECALC_REASON_DEFERRED_SHRINK = 5
} zlink_auto_hwm_recalc_reason_t;

typedef enum zlink_protocol_error_t
{
    ZLINK_PROTOCOL_ERROR_ZMP_MALFORMED_COMMAND_HELLO = 0x10000013
} zlink_protocol_error_t;

typedef enum zlink_spot_dispatch_event_t
{
    ZLINK_SPOT_DISPATCH_EVENT_SUBSCRIBE_READABLE = 1,
    ZLINK_SPOT_DISPATCH_EVENT_ROUTED_READABLE = 2,
    ZLINK_SPOT_DISPATCH_EVENT_TIMER_READABLE = 3,
    ZLINK_SPOT_DISPATCH_EVENT_CHANNEL_REPLY_READABLE = 4,
    ZLINK_SPOT_DISPATCH_EVENT_ACTOR_READABLE = 5,
    ZLINK_SPOT_DISPATCH_EVENT_ACTOR_JOIN_READABLE = 6
} zlink_spot_dispatch_event_t;

typedef enum zlink_spot_dispatch_subject_kind_t
{
    ZLINK_SPOT_DISPATCH_SUBJECT_SPOT = 1,
    ZLINK_SPOT_DISPATCH_SUBJECT_TIMER = 2,
    ZLINK_SPOT_DISPATCH_SUBJECT_CHANNEL_DEALER = 3,
    ZLINK_SPOT_DISPATCH_SUBJECT_ACTOR = 4
} zlink_spot_dispatch_subject_kind_t;

typedef enum zlink_monitor_source_kind_t
{
    ZLINK_MONITOR_SOURCE_SOCKET = 1,
    ZLINK_MONITOR_SOURCE_SPOT_PUB = 3,
    ZLINK_MONITOR_SOURCE_SPOT_SUB = 4
} zlink_monitor_source_kind_t;

typedef uint32_t zlink_socket_monitor_event_mask_t;

typedef enum zlink_socket_monitor_event_e
{
    ZLINK_SOCKET_MONITOR_EVENT_CONNECTED = 1u << 0,
    ZLINK_SOCKET_MONITOR_EVENT_CONNECT_DELAYED = 1u << 1,
    ZLINK_SOCKET_MONITOR_EVENT_CONNECT_RETRIED = 1u << 2,
    ZLINK_SOCKET_MONITOR_EVENT_LISTENING = 1u << 3,
    ZLINK_SOCKET_MONITOR_EVENT_BIND_FAILED = 1u << 4,
    ZLINK_SOCKET_MONITOR_EVENT_ACCEPTED = 1u << 5,
    ZLINK_SOCKET_MONITOR_EVENT_ACCEPT_FAILED = 1u << 6,
    ZLINK_SOCKET_MONITOR_EVENT_CLOSED = 1u << 7,
    ZLINK_SOCKET_MONITOR_EVENT_CLOSE_FAILED = 1u << 8,
    ZLINK_SOCKET_MONITOR_EVENT_DISCONNECTED = 1u << 9,
    ZLINK_SOCKET_MONITOR_EVENT_MONITOR_STOPPED = 1u << 10,
    ZLINK_SOCKET_MONITOR_EVENT_HANDSHAKE_FAILED_NO_DETAIL = 1u << 11,
    ZLINK_SOCKET_MONITOR_EVENT_CONNECTION_READY = 1u << 12,
    ZLINK_SOCKET_MONITOR_EVENT_HANDSHAKE_FAILED_PROTOCOL = 1u << 13,
    ZLINK_SOCKET_MONITOR_EVENT_HANDSHAKE_FAILED_AUTH = 1u << 14,
    ZLINK_SOCKET_MONITOR_EVENT_PEER_WEIGHT_CHANGED = 1u << 15,
    ZLINK_SOCKET_MONITOR_EVENT_ALL = 0xFFFFu,

    ZLINK_EVENT_CONNECTED = ZLINK_SOCKET_MONITOR_EVENT_CONNECTED,
    ZLINK_EVENT_CONNECT_DELAYED = ZLINK_SOCKET_MONITOR_EVENT_CONNECT_DELAYED,
    ZLINK_EVENT_CONNECT_RETRIED = ZLINK_SOCKET_MONITOR_EVENT_CONNECT_RETRIED,
    ZLINK_EVENT_LISTENING = ZLINK_SOCKET_MONITOR_EVENT_LISTENING,
    ZLINK_EVENT_BIND_FAILED = ZLINK_SOCKET_MONITOR_EVENT_BIND_FAILED,
    ZLINK_EVENT_ACCEPTED = ZLINK_SOCKET_MONITOR_EVENT_ACCEPTED,
    ZLINK_EVENT_ACCEPT_FAILED = ZLINK_SOCKET_MONITOR_EVENT_ACCEPT_FAILED,
    ZLINK_EVENT_CLOSED = ZLINK_SOCKET_MONITOR_EVENT_CLOSED,
    ZLINK_EVENT_CLOSE_FAILED = ZLINK_SOCKET_MONITOR_EVENT_CLOSE_FAILED,
    ZLINK_EVENT_DISCONNECTED = ZLINK_SOCKET_MONITOR_EVENT_DISCONNECTED,
    ZLINK_EVENT_MONITOR_STOPPED = ZLINK_SOCKET_MONITOR_EVENT_MONITOR_STOPPED,
    ZLINK_EVENT_HANDSHAKE_FAILED_NO_DETAIL =
      ZLINK_SOCKET_MONITOR_EVENT_HANDSHAKE_FAILED_NO_DETAIL,
    ZLINK_EVENT_CONNECTION_READY = ZLINK_SOCKET_MONITOR_EVENT_CONNECTION_READY,
    ZLINK_EVENT_HANDSHAKE_FAILED_PROTOCOL =
      ZLINK_SOCKET_MONITOR_EVENT_HANDSHAKE_FAILED_PROTOCOL,
    ZLINK_EVENT_HANDSHAKE_FAILED_AUTH =
      ZLINK_SOCKET_MONITOR_EVENT_HANDSHAKE_FAILED_AUTH,
    ZLINK_EVENT_PEER_WEIGHT_CHANGED =
      ZLINK_SOCKET_MONITOR_EVENT_PEER_WEIGHT_CHANGED,
    ZLINK_EVENT_ALL = ZLINK_SOCKET_MONITOR_EVENT_ALL
} zlink_socket_monitor_event_e;

typedef uint32_t zlink_monitor_state_mask_t;
typedef uint32_t zlink_monitor_snapshot_detail_mask_t;

typedef enum zlink_monitor_state_flag_e
{
    ZLINK_MONITOR_STATE_READY = 1u << 0,
    ZLINK_MONITOR_STATE_BOUND_READY = 1u << 1,
    ZLINK_MONITOR_STATE_CLOSED = 1u << 3
} zlink_monitor_state_flag_e;

typedef enum zlink_monitor_snapshot_detail_flag_e
{
    ZLINK_MONITOR_SNAPSHOT_DETAIL_SND_PENDING_MSGS = 1u << 1,
    ZLINK_MONITOR_SNAPSHOT_DETAIL_RCV_PENDING_MSGS = 1u << 2,
    ZLINK_MONITOR_SNAPSHOT_DETAIL_AUTO_HWM_BUDGET = 1u << 3,
    ZLINK_MONITOR_SNAPSHOT_DETAIL_AUTO_HWM_BUFFERS = 1u << 4
} zlink_monitor_snapshot_detail_flag_e;

typedef enum zlink_auto_connect_type_t
{
    ZLINK_AUTO_CONNECT_INVALID = 0,
    ZLINK_AUTO_CONNECT_ROUTE_MESH = 1,
    ZLINK_AUTO_CONNECT_CLIENT_SERVER = 2,
    ZLINK_AUTO_CONNECT_DEALER_MESH = 3,
    ZLINK_AUTO_CONNECT_FANOUT = 4,
    ZLINK_AUTO_CONNECT_SPOT_MESH = 5
} zlink_auto_connect_type_t;

typedef enum zlink_service_role_t
{
    ZLINK_SERVICE_ROLE_INVALID = 0,
    ZLINK_SERVICE_ROLE_SPOT = 2,
    ZLINK_SERVICE_ROLE_ROUTER = 3,
    ZLINK_SERVICE_ROLE_DEALER = 4,
    ZLINK_SERVICE_ROLE_PUB = 5,
    ZLINK_SERVICE_ROLE_SUB = 6
} zlink_service_role_t;

typedef zlink_service_role_t zlink_channel_role_t;

#define ZLINK_CHANNEL_ROLE_INVALID ZLINK_SERVICE_ROLE_INVALID
#define ZLINK_CHANNEL_ROLE_SPOT ZLINK_SERVICE_ROLE_SPOT
#define ZLINK_CHANNEL_ROLE_ROUTER ZLINK_SERVICE_ROLE_ROUTER
#define ZLINK_CHANNEL_ROLE_DEALER ZLINK_SERVICE_ROLE_DEALER
#define ZLINK_CHANNEL_ROLE_PUB ZLINK_SERVICE_ROLE_PUB
#define ZLINK_CHANNEL_ROLE_SUB ZLINK_SERVICE_ROLE_SUB

typedef enum zlink_spot_role_t
{
    ZLINK_SPOT_ROLE_PUB = 1,
    ZLINK_SPOT_ROLE_SUB = 2
} zlink_spot_role_t;

typedef enum zlink_service_kind_t
{
    ZLINK_SERVICE_KIND_DISCOVERY = 1,
    ZLINK_SERVICE_KIND_SPOT_SUB = 3,
    ZLINK_SERVICE_KIND_SPOT_PUB = 4,
    ZLINK_SERVICE_KIND_SOCKET = 5
} zlink_service_kind_t;

typedef uint32_t zlink_service_event_detail_mask_t;

typedef enum zlink_service_event_detail_flag_e
{
    ZLINK_SERVICE_EVENT_DETAIL_SERVICE_NAME = 1u << 0,
    ZLINK_SERVICE_EVENT_DETAIL_ENDPOINT = 1u << 1,
    ZLINK_SERVICE_EVENT_DETAIL_SUBJECT_RID = 1u << 2,
    ZLINK_SERVICE_EVENT_DETAIL_PEER_RID = 1u << 3,
    ZLINK_SERVICE_EVENT_DETAIL_SUBJECT = 1u << 4,
    ZLINK_SERVICE_EVENT_DETAIL_SUBJECT_KIND = 1u << 5,

    ZLINK_EVENT_DETAIL_SERVICE_NAME = ZLINK_SERVICE_EVENT_DETAIL_SERVICE_NAME,
    ZLINK_EVENT_DETAIL_ENDPOINT = ZLINK_SERVICE_EVENT_DETAIL_ENDPOINT,
    ZLINK_EVENT_DETAIL_SUBJECT_RID = ZLINK_SERVICE_EVENT_DETAIL_SUBJECT_RID,
    ZLINK_EVENT_DETAIL_PEER_RID = ZLINK_SERVICE_EVENT_DETAIL_PEER_RID,
    ZLINK_EVENT_DETAIL_SUBJECT = ZLINK_SERVICE_EVENT_DETAIL_SUBJECT,
    ZLINK_EVENT_DETAIL_SUBJECT_KIND = ZLINK_SERVICE_EVENT_DETAIL_SUBJECT_KIND
} zlink_service_event_detail_flag_e;

typedef enum zlink_service_event_subject_kind_t
{
    ZLINK_SERVICE_EVENT_SUBJECT_NONE = 0,
    ZLINK_SERVICE_EVENT_SUBJECT_TOPIC = 1,
    ZLINK_SERVICE_EVENT_SUBJECT_PATTERN = 2
} zlink_service_event_subject_kind_t;

typedef enum zlink_spot_node_state_t
{
    ZLINK_SPOT_NODE_STATE_IDLE = 1,
    ZLINK_SPOT_NODE_STATE_CONNECTING = 2,
    ZLINK_SPOT_NODE_STATE_PARTIAL_READY = 3,
    ZLINK_SPOT_NODE_STATE_READY = 4,
    ZLINK_SPOT_NODE_STATE_ERROR = 5
} zlink_spot_node_state_t;

typedef enum zlink_spot_peer_source_t
{
    ZLINK_SPOT_PEER_SOURCE_MANUAL = 1,
    ZLINK_SPOT_PEER_SOURCE_DISCOVERY = 2,
    ZLINK_SPOT_PEER_SOURCE_MIXED = 3
} zlink_spot_peer_source_t;

typedef enum zlink_spot_peer_state_t
{
    ZLINK_SPOT_PEER_STATE_CONFIGURED = 1,
    ZLINK_SPOT_PEER_STATE_CONNECTING = 2,
    ZLINK_SPOT_PEER_STATE_CONNECTED = 3
} zlink_spot_peer_state_t;

typedef enum zlink_registry_state_t
{
    ZLINK_REGISTRY_STATE_IDLE = 1,
    ZLINK_REGISTRY_STATE_ACTIVE = 2,
    ZLINK_REGISTRY_STATE_DEGRADED = 3,
    ZLINK_REGISTRY_STATE_ERROR = 4
} zlink_registry_state_t;

typedef enum zlink_topology_source_t
{
    ZLINK_TOPOLOGY_SOURCE_MANUAL = 1,
    ZLINK_TOPOLOGY_SOURCE_DISCOVERY = 2,
    ZLINK_TOPOLOGY_SOURCE_REGISTRY = 3
} zlink_topology_source_t;

typedef enum zlink_topology_state_t
{
    ZLINK_TOPOLOGY_STATE_DISCOVERED = 1,
    ZLINK_TOPOLOGY_STATE_CONNECTING = 2,
    ZLINK_TOPOLOGY_STATE_READY = 3,
    ZLINK_TOPOLOGY_STATE_LOST = 4,
    ZLINK_TOPOLOGY_STATE_ERROR = 5,
    ZLINK_TOPOLOGY_STATE_STOPPED = 6
} zlink_topology_state_t;

typedef enum zlink_poller_source_kind_t
{
    ZLINK_POLLER_SOURCE_SOCKET = 1,
    ZLINK_POLLER_SOURCE_FD = 2,
    ZLINK_POLLER_SOURCE_TIMER = 3
} zlink_poller_source_kind_t;

typedef enum zlink_send_flags_t
{
    ZLINK_SEND_FLAGS_NONE     = 0,
    ZLINK_SEND_FLAGS_DONTWAIT = 0x0001u
} zlink_send_flags_t;

typedef enum zlink_recv_flags_t
{
    ZLINK_RECV_FLAGS_NONE     = 0,
    ZLINK_RECV_FLAGS_DONTWAIT = 0x0001u
} zlink_recv_flags_t;

typedef short zlink_poller_event_mask_t;

typedef enum zlink_poller_event_flag_e
{
    ZLINK_POLLIN = 1,
    ZLINK_POLLOUT = 2,
    ZLINK_POLLERR = 4,
    ZLINK_POLLPRI = 8,
    ZLINK_POLLITEMS_DFLT = 16
} zlink_poller_event_flag_e;

#endif
