#ifndef ZLINK_LEGACY_INTERNAL_H_INCLUDED
#define ZLINK_LEGACY_INTERNAL_H_INCLUDED

#ifdef ZLINK_INTERNAL_BUILD

#define ZLINK_PAIR ((zlink_socket_type_t) 0)
#define ZLINK_PUB ((zlink_socket_type_t) 1)
#define ZLINK_SUB ((zlink_socket_type_t) 2)
#define ZLINK_DEALER ((zlink_socket_type_t) 5)
#define ZLINK_ROUTER ((zlink_socket_type_t) 6)
#define ZLINK_XPUB ((zlink_socket_type_t) 9)
#define ZLINK_XSUB ((zlink_socket_type_t) 10)
#define ZLINK_STREAM ((zlink_socket_type_t) 11)

enum
{
    ZLINK_SOCKOPT_AFFINITY = 0x1101,
    ZLINK_SOCKOPT_ROUTING_ID = 0x1102,
    ZLINK_SOCKOPT_SUBSCRIBE = 0x1103,
    ZLINK_SOCKOPT_UNSUBSCRIBE = 0x1104,
    ZLINK_SOCKOPT_RATE = 0x1105,
    ZLINK_SOCKOPT_RECOVERY_IVL = 0x1106,
    ZLINK_SOCKOPT_SNDBUF = 0x1107,
    ZLINK_SOCKOPT_RCVBUF = 0x1108,
    ZLINK_SOCKOPT_FD = 0x110A,
    ZLINK_SOCKOPT_EVENTS = 0x110B,
    ZLINK_SOCKOPT_TYPE = 0x110C,
    ZLINK_SOCKOPT_LINGER = 0x110D,
    ZLINK_SOCKOPT_RECONNECT_IVL = 0x110E,
    ZLINK_SOCKOPT_BACKLOG = 0x110F,
    ZLINK_SOCKOPT_RECONNECT_IVL_MAX = 0x1110,
    ZLINK_SOCKOPT_MAXMSGSIZE = 0x1111,
    ZLINK_SOCKOPT_SNDHWM = 0x1112,
    ZLINK_SOCKOPT_RCVHWM = 0x1113,
    ZLINK_SOCKOPT_MULTICAST_HOPS = 0x1114,
    ZLINK_SOCKOPT_RCVTIMEO = 0x1115,
    ZLINK_SOCKOPT_SNDTIMEO = 0x1116,
    ZLINK_SOCKOPT_LAST_ENDPOINT = 0x1117,
    ZLINK_SOCKOPT_ROUTER_MANDATORY = 0x1118,
    ZLINK_SOCKOPT_TCP_KEEPALIVE = 0x1119,
    ZLINK_SOCKOPT_TCP_KEEPALIVE_CNT = 0x111A,
    ZLINK_SOCKOPT_TCP_KEEPALIVE_IDLE = 0x111B,
    ZLINK_SOCKOPT_TCP_KEEPALIVE_INTVL = 0x111C,
    ZLINK_SOCKOPT_IMMEDIATE = 0x111D,
    ZLINK_SOCKOPT_XPUB_VERBOSE = 0x111E,
    ZLINK_SOCKOPT_IPV6 = 0x111F,
    ZLINK_SOCKOPT_PROBE_ROUTER = 0x1120,
    ZLINK_SOCKOPT_CONFLATE = 0x1121,
    ZLINK_SOCKOPT_ROUTER_HANDOVER = 0x1122,
    ZLINK_SOCKOPT_TOS = 0x1123,
    ZLINK_SOCKOPT_CONNECT_ROUTING_ID = 0x1124,
    ZLINK_SOCKOPT_HANDSHAKE_IVL = 0x1125,
    ZLINK_SOCKOPT_XPUB_NODROP = 0x1126,
    ZLINK_SOCKOPT_BLOCKY = 0x1127,
    ZLINK_SOCKOPT_XPUB_MANUAL = 0x1128,
    ZLINK_SOCKOPT_XPUB_WELCOME_MSG = 0x1129,
    ZLINK_SOCKOPT_STREAM_NOTIFY = 0x112A,
    ZLINK_SOCKOPT_INVERT_MATCHING = 0x112B,
    ZLINK_SOCKOPT_HEARTBEAT_IVL = 0x112C,
    ZLINK_SOCKOPT_HEARTBEAT_TTL = 0x112D,
    ZLINK_SOCKOPT_HEARTBEAT_TIMEOUT = 0x112E,
    ZLINK_SOCKOPT_XPUB_VERBOSER = 0x112F,
    ZLINK_SOCKOPT_CONNECT_TIMEOUT = 0x1130,
    ZLINK_SOCKOPT_TCP_MAXRT = 0x1131,
    ZLINK_SOCKOPT_MULTICAST_MAXTPDU = 0x1132,
    ZLINK_SOCKOPT_BINDTODEVICE = 0x1134,
    ZLINK_SOCKOPT_TLS_CERT = 0x1135,
    ZLINK_SOCKOPT_TLS_KEY = 0x1136,
    ZLINK_SOCKOPT_TLS_CA = 0x1137,
    ZLINK_SOCKOPT_TLS_VERIFY = 0x1138,
    ZLINK_SOCKOPT_XPUB_MANUAL_LAST_VALUE = 0x1139,
    ZLINK_SOCKOPT_TLS_REQUIRE_CLIENT_CERT = 0x113A,
    ZLINK_SOCKOPT_TLS_HOSTNAME = 0x113B,
    ZLINK_SOCKOPT_TLS_TRUST_SYSTEM = 0x113C,
    ZLINK_SOCKOPT_TLS_PASSWORD = 0x113D,
    ZLINK_SOCKOPT_ONLY_FIRST_SUBSCRIBE = 0x113E,
    ZLINK_SOCKOPT_TOPICS_COUNT = 0x113F,
    ZLINK_SOCKOPT_ZMP_METADATA = 0x1140,
    ZLINK_SOCKOPT_TCP_NODELAY = 0x1141
};

#define ZLINK_INTERNAL_OPT_AFFINITY 4
#define ZLINK_INTERNAL_OPT_ROUTING_ID 5
#define ZLINK_INTERNAL_OPT_SUBSCRIBE 6
#define ZLINK_INTERNAL_OPT_UNSUBSCRIBE 7
#define ZLINK_INTERNAL_OPT_RATE 8
#define ZLINK_INTERNAL_OPT_RECOVERY_IVL 9
#define ZLINK_INTERNAL_OPT_SNDBUF 11
#define ZLINK_INTERNAL_OPT_RCVBUF 12
#define ZLINK_INTERNAL_OPT_LINGER 17
#define ZLINK_INTERNAL_OPT_RECONNECT_IVL 18
#define ZLINK_INTERNAL_OPT_BACKLOG 19
#define ZLINK_INTERNAL_OPT_RECONNECT_IVL_MAX 21
#define ZLINK_INTERNAL_OPT_MAXMSGSIZE 22
#define ZLINK_INTERNAL_OPT_SNDHWM 23
#define ZLINK_INTERNAL_OPT_RCVHWM 24
#define ZLINK_INTERNAL_OPT_MULTICAST_HOPS 25
#define ZLINK_INTERNAL_OPT_RCVTIMEO 27
#define ZLINK_INTERNAL_OPT_SNDTIMEO 28
#define ZLINK_INTERNAL_OPT_ROUTER_MANDATORY 33
#define ZLINK_INTERNAL_OPT_TCP_KEEPALIVE 34
#define ZLINK_INTERNAL_OPT_TCP_KEEPALIVE_CNT 35
#define ZLINK_INTERNAL_OPT_TCP_KEEPALIVE_IDLE 36
#define ZLINK_INTERNAL_OPT_TCP_KEEPALIVE_INTVL 37
#define ZLINK_INTERNAL_OPT_IMMEDIATE 39
#define ZLINK_INTERNAL_OPT_XPUB_VERBOSE 40
#define ZLINK_INTERNAL_OPT_IPV6 42
#define ZLINK_INTERNAL_OPT_PROBE_ROUTER 51
#define ZLINK_INTERNAL_OPT_CONFLATE 54
#define ZLINK_INTERNAL_OPT_ROUTER_HANDOVER 56
#define ZLINK_INTERNAL_OPT_TOS 57
#define ZLINK_INTERNAL_OPT_CONNECT_ROUTING_ID 61
#define ZLINK_INTERNAL_OPT_HANDSHAKE_IVL 66
#define ZLINK_INTERNAL_OPT_XPUB_NODROP 69
#define ZLINK_INTERNAL_OPT_BLOCKY 70
#define ZLINK_INTERNAL_OPT_XPUB_MANUAL 71
#define ZLINK_INTERNAL_OPT_XPUB_WELCOME_MSG 72
#define ZLINK_INTERNAL_OPT_STREAM_NOTIFY 73
#define ZLINK_INTERNAL_OPT_INVERT_MATCHING 74
#define ZLINK_INTERNAL_OPT_HEARTBEAT_IVL 75
#define ZLINK_INTERNAL_OPT_HEARTBEAT_TTL 76
#define ZLINK_INTERNAL_OPT_HEARTBEAT_TIMEOUT 77
#define ZLINK_INTERNAL_OPT_XPUB_VERBOSER 78
#define ZLINK_INTERNAL_OPT_CONNECT_TIMEOUT 79
#define ZLINK_INTERNAL_OPT_TCP_MAXRT 80
#define ZLINK_INTERNAL_OPT_MULTICAST_MAXTPDU 84
#define ZLINK_INTERNAL_OPT_BINDTODEVICE 92
#define ZLINK_INTERNAL_OPT_TLS_CERT 95
#define ZLINK_INTERNAL_OPT_TLS_KEY 96
#define ZLINK_INTERNAL_OPT_TLS_CA 97
#define ZLINK_INTERNAL_OPT_TLS_VERIFY 98
#define ZLINK_INTERNAL_OPT_XPUB_MANUAL_LAST_VALUE 98
#define ZLINK_INTERNAL_OPT_TLS_REQUIRE_CLIENT_CERT 99
#define ZLINK_INTERNAL_OPT_TLS_HOSTNAME 100
#define ZLINK_INTERNAL_OPT_TLS_TRUST_SYSTEM 101
#define ZLINK_INTERNAL_OPT_TLS_PASSWORD 102
#define ZLINK_INTERNAL_OPT_ONLY_FIRST_SUBSCRIBE 108
#define ZLINK_INTERNAL_OPT_TOPICS_COUNT 116
#define ZLINK_INTERNAL_OPT_ZMP_METADATA 117
#define ZLINK_INTERNAL_OPT_TCP_NODELAY 118
#define ZLINK_INTERNAL_OPT_FD ZLINK_SOCKOPT_FD
#define ZLINK_INTERNAL_OPT_EVENTS ZLINK_SOCKOPT_EVENTS
#define ZLINK_INTERNAL_OPT_TYPE ZLINK_SOCKOPT_TYPE
#define ZLINK_INTERNAL_OPT_LAST_ENDPOINT ZLINK_SOCKOPT_LAST_ENDPOINT

typedef enum zlink_registry_socket_role_t
{
    ZLINK_REGISTRY_SOCKET_PUB = 1,
    ZLINK_REGISTRY_SOCKET_ROUTER = 2,
    ZLINK_REGISTRY_SOCKET_PEER_SUB = 3
} zlink_registry_socket_role_t;

typedef enum zlink_spot_pub_option_t
{
    ZLINK_SPOT_PUB_OPT_SNDHWM = 0x2201,
    ZLINK_SPOT_PUB_OPT_SNDTIMEO = 0x2202,
    ZLINK_SPOT_PUB_OPT_LINGER = 0x2203,
    ZLINK_SPOT_PUB_OPT_NODROP = 0x2204,
    ZLINK_SPOT_PUB_OPT_SNDBUF = 0x2208,
    ZLINK_SPOT_PUB_OPT_RCVBUF = 0x2209
} zlink_spot_pub_option_t;

typedef enum zlink_spot_sub_option_t
{
    ZLINK_SPOT_SUB_OPT_RCVHWM = 0x2301,
    ZLINK_SPOT_SUB_OPT_LINGER = 0x2302,
    ZLINK_SPOT_SUB_OPT_SNDBUF = 0x2303,
    ZLINK_SPOT_SUB_OPT_RCVBUF = 0x2304,
    ZLINK_SPOT_SUB_OPT_RCVTIMEO = 0x2305
} zlink_spot_sub_option_t;
#endif

#endif
