<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageId>Systems.Zlink.Codecs.Json</PackageId>
    <RootNamespace>Systems.Zlink.Codecs.Json</RootNamespace>
    <Version>5.3.4</Version>
    <Description>JSON codec extension for Systems.Zlink</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Zlink/Zlink.csproj" />
  </ItemGroup>
</Project>
