'use strict';
Object.defineProperty(exports, "__esModule", { value: true });
const test = require('node:test');
const assert = require('node:assert/strict');
const zlink = require('../dist');
test('routing id accepts 255-byte maximum and rejects overflow', () => {
    const ctx = new zlink.Context();
    const dealer = new zlink.DealerSocket(ctx);
    const router = new zlink.RouterSocket(ctx);
    const stream = new zlink.StreamSocket(ctx);
    const compat = new zlink.Socket(ctx, zlink.SocketType.STREAM);
    const maxRoutingId = Buffer.alloc(255, 0x61);
    const overflowRoutingId = Buffer.alloc(256, 0x62);
    assert.doesNotThrow(() => dealer.setRoutingId(maxRoutingId));
    assert.throws(() => dealer.setRoutingId(overflowRoutingId), /at most 255 bytes/);
    assert.throws(() => router.send(overflowRoutingId, zlink.Message.empty()), /at most 255 bytes/);
    assert.throws(() => router.trySend(overflowRoutingId, zlink.Message.empty()), /at most 255 bytes/);
    assert.throws(() => stream.send(overflowRoutingId, zlink.Message.empty()), /at most 255 bytes/);
    assert.throws(() => compat.streamSend(overflowRoutingId, Buffer.alloc(0)), /255 bytes/);
    compat.close();
    stream.close();
    router.close();
    dealer.close();
    ctx.close();
});
