'use strict';
Object.defineProperty(exports, "__esModule", { value: true });
const test = require('node:test');
const assert = require('node:assert/strict');
const zlink = require('@zlink-systems/zlink');
test('public flag and result enums stay frozen', () => {
    assert.equal(zlink.SendFlags.None, 0);
    assert.equal(zlink.SendFlags.DontWait, 1);
    assert.equal(zlink.RecvFlags.None, 0);
    assert.equal(zlink.RecvFlags.DontWait, 1);
    assert.equal(zlink.SubmitResult.NotSupported, 7);
    assert.equal(zlink.RequestResult.ProtocolError, 104);
    assert.equal(zlink.RequestResult.NotSupported, 112);
    assert.equal(zlink.RecvResult.NoData, 201);
    assert.equal(zlink.SpotDispatchEvent.ActorReadable, 5);
    assert.equal(zlink.SpotDispatchEvent.ActorJoinReadable, 6);
    assert.equal(zlink.SpotDispatchSubjectKind.Actor, 4);
    assert.equal(zlink.AutoHwmProfile.Compact, 0);
    assert.equal(zlink.AutoHwmProfile.LowLatency, 1);
    assert.equal(zlink.AutoHwmProfile.Balanced, 2);
    assert.equal(zlink.AutoHwmProfile.Throughput, 3);
    assert.equal(zlink.SpotRole.Pub, 1);
    assert.equal(zlink.SpotPeerSource.Manual, 1);
    assert.equal(zlink.SpotPeerKind.RouterChannel, 2);
    assert.equal(zlink.SpotPeerState.Connected, 3);
    assert.equal(zlink.SpotNodeState.Ready, 4);
    assert.equal(zlink.SpotNodeSocketOwner.Spot, 2);
    assert.ok(Object.isFrozen(zlink.SendFlags));
    assert.ok(Object.isFrozen(zlink.RecvFlags));
    assert.ok(Object.isFrozen(zlink.SubmitResult));
    assert.ok(Object.isFrozen(zlink.RequestResult));
    assert.ok(Object.isFrozen(zlink.SpotDispatchEvent));
    assert.ok(Object.isFrozen(zlink.SpotDispatchSubjectKind));
    assert.ok(Object.isFrozen(zlink.AutoHwmProfile));
    assert.ok(Object.isFrozen(zlink.SpotRole));
    assert.ok(Object.isFrozen(zlink.SpotPeerSource));
    assert.ok(Object.isFrozen(zlink.SpotPeerKind));
    assert.ok(Object.isFrozen(zlink.SpotPeerState));
    assert.ok(Object.isFrozen(zlink.SpotNodeState));
    assert.ok(Object.isFrozen(zlink.SpotNodeSocketOwner));
    assert.ok(Object.isFrozen(zlink.MonitorEventType));
    assert.ok(Object.isFrozen(zlink.MonitorSourceKind));
    assert.ok(Object.isFrozen(zlink.SocketType));
});
test('compat enums and errno helper are not public', () => {
    assert.ok(Object.isFrozen(zlink.MonitorEvent));
    assert.equal(zlink.errno, undefined);
    assert.equal(zlink.ContextOption, undefined);
    assert.equal(zlink.SocketOption, undefined);
    assert.equal(zlink.MonitorState, undefined);
    assert.equal(zlink.MonitorStatusDetail, undefined);
    assert.equal(zlink.ServiceMonitorEvent, undefined);
    assert.equal(zlink.ServiceType, undefined);
    assert.equal(zlink.AutoConnectType, undefined);
    assert.equal(zlink.ServiceRole, undefined);
    assert.equal(zlink.ServiceKind, undefined);
    assert.equal(zlink.RegistryState, undefined);
    assert.equal(zlink.TopologySource, undefined);
    assert.equal(zlink.TopologyState, undefined);
    assert.equal(zlink.Subscribed, undefined);
    assert.equal(zlink.AUTO_CONNECT_SPOT_MESH, undefined);
    assert.equal(zlink.AUTO_CONNECT_CLIENT_SERVER, undefined);
    assert.equal(zlink.METADATA_KEY_USER_MIN, undefined);
    assert.equal(zlink.METADATA_VALUE_MAX, undefined);
});
