'use strict';
Object.defineProperty(exports, "__esModule", { value: true });
const test = require('node:test');
const assert = require('node:assert/strict');
const zlink = require('../dist/canonical');
test('public flag and result enums stay frozen', () => {
    assert.equal(zlink.SendFlags.None, 0);
    assert.equal(zlink.SendFlags.DontWait, 1);
    assert.equal(zlink.RecvFlags.None, 0);
    assert.equal(zlink.RecvFlags.DontWait, 1);
    assert.equal(zlink.SubmitResult.NotSupported, 7);
    assert.equal(zlink.RequestResult.ProtocolError, 104);
    assert.equal(zlink.RecvResult.NoData, 201);
    assert.ok(Object.isFrozen(zlink.SendFlags));
    assert.ok(Object.isFrozen(zlink.RecvFlags));
    assert.ok(Object.isFrozen(zlink.SubmitResult));
    assert.ok(Object.isFrozen(zlink.RequestResult));
});
test('compat enums and errno helper are not public', () => {
    assert.ok(Object.isFrozen(zlink.MonitorEvent));
    assert.equal(zlink.errno, undefined);
    assert.equal(zlink.ContextOption, undefined);
    assert.equal(zlink.SocketType, undefined);
    assert.equal(zlink.SocketOption, undefined);
    assert.equal(zlink.MonitorSourceKind, undefined);
    assert.equal(zlink.MonitorState, undefined);
    assert.equal(zlink.MonitorSnapshotDetail, undefined);
    assert.equal(zlink.ServiceMonitorEvent, undefined);
    assert.equal(zlink.ServiceType, undefined);
    assert.equal(zlink.SERVICE_TYPE_SPOT, undefined);
    assert.equal(zlink.SERVICE_TYPE_SOCKET, undefined);
    assert.equal(zlink.ServiceRole, undefined);
    assert.equal(zlink.ServiceKind, undefined);
    assert.equal(zlink.SpotPeerSource, undefined);
    assert.equal(zlink.SpotPeerState, undefined);
    assert.equal(zlink.SpotNodeState, undefined);
    assert.equal(zlink.RegistryState, undefined);
    assert.equal(zlink.TopologySource, undefined);
    assert.equal(zlink.TopologyState, undefined);
    assert.equal(zlink.METADATA_KEY_USER_MIN, undefined);
    assert.equal(zlink.METADATA_VALUE_MAX, undefined);
});
