'use strict';
Object.defineProperty(exports, "__esModule", { value: true });
const test = require('node:test');
const assert = require('node:assert/strict');
const zlink = require('@zlink-systems/zlink');
test('request-reply helpers expose canonical socket accessors', () => {
    const ctx = new zlink.Context();
    const routerSocket = new zlink.RouterSocket(ctx);
    const dealerSocket = new zlink.DealerSocket(ctx);
    assert.equal(typeof routerSocket.request, 'function');
    assert.equal(typeof routerSocket.reply, 'function');
    assert.equal(typeof routerSocket.requestToSpot, 'function');
    assert.equal(typeof routerSocket.replyToSpot, 'function');
    assert.equal(typeof routerSocket.recv, 'function');
    assert.equal(routerSocket.onReceive, undefined);
    assert.equal(typeof dealerSocket.request, 'function');
    assert.equal(typeof dealerSocket.recv, 'function');
    assert.equal(dealerSocket.onReceive, undefined);
    dealerSocket.close();
    routerSocket.close();
    ctx.close();
});
test('router recv and reply still work through the canonical socket surface', () => {
    const ctx = new zlink.Context();
    const routerSocket = new zlink.RouterSocket(ctx);
    const dealerSocket = new zlink.DealerSocket(ctx);
    const clientRoutingId = zlink.RoutingId.from(Buffer.from('request-reply-client'));
    routerSocket.bind('inproc://request-reply-contract');
    dealerSocket.setRoutingId(clientRoutingId);
    dealerSocket.connect('inproc://request-reply-contract');
    dealerSocket.send().message('ping').submit();
    const request = new zlink.Received();
    routerSocket.recv(request);
    assert.ok(request.routingId instanceof zlink.RoutingId);
    assert.equal(request.routingId.toBytes().toString(), 'request-reply-client');
    assert.equal(request.requestSeq, null);
    assert.equal(request.parts[0].data().toString(), 'ping');
    routerSocket.send(request.routingId).message('pong').submit();
    const reply = new zlink.Received();
    dealerSocket.recv(reply);
    assert.equal(reply.parts[0].data().toString(), 'pong');
    assert.equal(reply.requestSeq, null);
    dealerSocket.close();
    routerSocket.close();
    ctx.close();
});
test('reply helpers reject non-none flags when the core lacks reply flag support', () => {
    const ctx = new zlink.Context();
    const routerSocket = new zlink.RouterSocket(ctx);
    const spotNode = new zlink.SpotNode(ctx);
    const spot = spotNode.createSpot();
    const routingId = zlink.RoutingId.from(Buffer.from('peer'));
    const spotRoutingId = zlink.RoutingId.from(Buffer.from('spot'));
    assert.throws(() => routerSocket.reply(routingId, 1n).message('pong').flags(zlink.SendFlags.DontWait).submit(), (error) => error instanceof zlink.SubmitError && error.result === zlink.SubmitResult.NotSupported);
    assert.throws(() => routerSocket.replyToSpot(routingId, spotRoutingId, 1n).message('pong').flags(zlink.SendFlags.DontWait).submit(), (error) => error instanceof zlink.SubmitError && error.result === zlink.SubmitResult.NotSupported);
    assert.equal(typeof spot.sendToSpot, 'function');
    assert.equal(typeof spot.replyToSpot, 'function');
    assert.equal(typeof spot.replyToRouter, 'function');
    assert.throws(() => spot.replyToSpot(routingId, spotRoutingId, 1n).message('pong').flags(zlink.SendFlags.DontWait).submit(), (error) => error instanceof zlink.SubmitError && error.result === zlink.SubmitResult.NotSupported);
    assert.throws(() => spot.replyToRouter(routingId, 1n).message('pong').flags(zlink.SendFlags.DontWait).submit(), (error) => error instanceof zlink.SubmitError && error.result === zlink.SubmitResult.NotSupported);
    spot.close();
    spotNode.close();
    routerSocket.close();
    ctx.close();
});
