'use strict';
Object.defineProperty(exports, "__esModule", { value: true });
const test = require('node:test');
const assert = require('node:assert/strict');
const zlink = require('../dist');
test('xpub exposes subscription events and dedicated option helpers', () => {
    const ctx = new zlink.Context();
    const xpub = new zlink.XPubSocket(ctx);
    const xsub = new zlink.XSubSocket(ctx);
    xpub.bind('inproc://xpub-events');
    xsub.connect('inproc://xpub-events');
    xpub.setVerbose(true);
    xpub.setVerboser(true);
    xpub.setNoDrop(true);
    xsub.setSubscription('topic');
    assert.equal(zlink.SocketOption.XPUB_VERBOSE, 0x3301);
    const event = xpub.receiveSubscriptionEvent();
    assert.equal(event.topic, 'topic');
    assert.equal(event.subscribed, true);
    assert.equal(xpub.tryReceiveSubscriptionEvent(), null);
    xsub.close();
    xpub.close();
    ctx.close();
});
