[package]
name = "zlink-codec-protobuf"
version = "5.3.4"
edition = "2024"
rust-version = "1.85"
description = "Protobuf codec extension for the zlink Rust bindings"
license = "MPL-2.0"
homepage = "https://zlink.systems/"

[dependencies]
prost = "0.13"
zlink = { version = "5.3.4", path = "../.." }

[dev-dependencies]
prost = { version = "0.13", features = ["derive"] }
