# SPDX-License-Identifier: MPL-2.0

from typing import Protocol, runtime_checkable


@runtime_checkable
class Actor(Protocol):
    def ref(self): ...

    @property
    def actor_ref(self): ...

    def join(self, spot): ...

    def leave(self, spot): ...

    def recv_part(self, *, flags=0): ...

    def send_bound_session(self): ...

    def close_bound_session(self, *, timeout=0): ...

    def close(self, *args, **kwargs): ...

    def __enter__(self): ...

    def __exit__(self, exc_type, exc, tb): ...

    async def __aenter__(self): ...

    async def __aexit__(self, exc_type, exc, tb): ...


__all__ = ["Actor"]
