# SPDX-License-Identifier: MPL-2.0

from ...core.options import AutoHwmProfile
from ..codes import SpotNodeMode
from . import spot as _spot_contract


class SpotNode:
    def __new__(cls, ctx, mode: int | SpotNodeMode | None = None):
        if cls is SpotNode:
            return _spot_contract._require(
                _spot_contract._spot_node_factory, "spot node"
            )(ctx, mode)
        return object.__new__(cls)

    def set_pub_bind(self, endpoint: str): ...
    def set_router_bind(self, endpoint: str): ...
    def last_endpoint(self) -> str: ...
    def connect_peer(self, endpoint: str): ...
    def disconnect_peer(self, endpoint: str): ...
    def disconnect_peer_rid(self, target_node_rid): ...
    def connect_router_channel_peer(self, channel_name: str, endpoint: str): ...
    def disconnect_router_channel_peer(self, channel_name: str, endpoint: str): ...
    def disconnect_router_channel_peer_rid(self, channel_name: str, peer_rid): ...
    def attach_discovery(self, discovery): ...
    def attach_spot_route_channel_discovery(self, channel_name: str, discovery): ...
    def attach_channel_dealer(self, discovery, dealer): ...
    def attach_channel_dealer_manual(self, channel_name, dealer): ...
    def attach_pub_ingress(self, pub): ...
    def set_router_hwm(self, value: int): ...
    def set_pubsub_hwm(self, value: int): ...
    def set_router_hwm_profile(self, value: int | AutoHwmProfile): ...
    def set_pubsub_hwm_profile(self, value: int | AutoHwmProfile): ...

    @property
    def router_hwm_profile(self): ...
    @router_hwm_profile.setter
    def router_hwm_profile(self, value): ...
    @property
    def router_hwm(self): ...
    @router_hwm.setter
    def router_hwm(self, value): ...
    @property
    def pubsub_hwm_profile(self): ...
    @pubsub_hwm_profile.setter
    def pubsub_hwm_profile(self, value): ...
    @property
    def pubsub_hwm(self): ...
    @pubsub_hwm.setter
    def pubsub_hwm(self, value): ...
    @property
    def dispatch_workers_min(self): ...
    @dispatch_workers_min.setter
    def dispatch_workers_min(self, value: int): ...
    @property
    def dispatch_workers_max(self): ...
    @dispatch_workers_max.setter
    def dispatch_workers_max(self, value: int): ...

    def create_spot(self): ...
    def entry_spot(self): ...
    def spot_lookup(self, spot_rid): ...
    def get_or_create_spot(self, spot_rid): ...
    def actor(self, actor_id): ...
    def actor_lookup(self, actor_id): ...
    def destroy_actor(self, actor_ref): ...
    def remote_actor_get_ref(self, target_node_rid, actor_id): ...
    def join_actor(self, actor_ref, dest_node_rid, dest_spot_rid): ...
    def join_actor_entry_spot(self, actor_ref, dest_node_rid): ...
    def leave_actor(self, actor_ref, current_spot_rid): ...
    def send_bound_session_msg(self, actor_ref): ...
    def spots(self): ...
    def actors(self): ...
    def set_routing_id(self, routing_id): ...
    def get_routing_id(self): ...
    @property
    def routing_id(self): ...
    def set_tls_server(self, cert: str, key: str, require_client_cert: bool = False): ...
    def set_tls_client(
        self, ca_cert: str | None, hostname: str | None, trust_system: bool = False
    ): ...
    def status(self): ...
    def peers(self): ...
    def peers_query(self, filter_=None): ...
    def subjects(self, filter_=None): ...
    def internal_sockets(self, filter_=None): ...

    def close(self, *args, **kwargs): ...

    def __enter__(self): ...

    def __exit__(self, exc_type, exc, tb): ...

    async def __aenter__(self): ...

    async def __aexit__(self, exc_type, exc, tb): ...


__all__ = ["SpotNode"]
