# SPDX-License-Identifier: MPL-2.0

from typing import Protocol, runtime_checkable

from ...core.options import AutoHwmProfile
from ..codes import SpotNodeMode
from . import spot as _spot_contract


@runtime_checkable
class SpotNode(Protocol):
    """A spot node: hosts spots and actors, tunes their sockets, and exposes the
    node's peers, subjects, and topology. Supports the context-manager
    protocol."""

    def set_pub_bind(self, endpoint: str):
        """Set the publish endpoint the node binds to."""
        ...
    def set_router_bind(self, endpoint: str):
        """Set the router endpoint the node binds to."""
        ...
    def last_endpoint(self) -> str: ...
    def connect_peer(self, endpoint: str):
        """Connect to a peer node at ``endpoint``."""
        ...
    def disconnect_peer(self, endpoint: str):
        """Disconnect the peer previously connected at ``endpoint``."""
        ...
    def disconnect_peer_rid(self, target_node_rid):
        """Disconnect the peer identified by ``target_node_rid``."""
        ...
    def connect_router_channel_peer(self, channel_name: str, endpoint: str):
        """Connect to a router-channel peer on ``channel_name`` at ``endpoint``."""
        ...
    def connect_router_channel_peer_rid(self, channel_name: str, peer_rid, endpoint: str):
        """Connect to a router-channel peer on ``channel_name`` by ``peer_rid`` at ``endpoint``."""
        ...
    def disconnect_router_channel_peer(self, channel_name: str, endpoint: str):
        """Disconnect a router-channel peer on ``channel_name`` at ``endpoint``."""
        ...
    def disconnect_router_channel_peer_rid(self, channel_name: str, peer_rid):
        """Disconnect a router-channel peer on ``channel_name`` by ``peer_rid``."""
        ...
    def attach_discovery(self, discovery):
        """Attach a discovery service so the node auto-connects discovered peers."""
        ...
    def attach_spot_route_channel_discovery(self, channel_name: str, discovery):
        """Attach a discovery service for the spot-route channel ``channel_name``."""
        ...
    def attach_pub_ingress(self, pub):
        """Attach a PUB socket as a publish ingress for the node."""
        ...
    def create_route_bridge(self, options=None):
        """Create a bridge that uses caller-owned channel sockets for SPOT routing."""
        ...
    def create_publisher(self):
        """Create a publisher handle for the local SPOT topic plane."""
        ...
    def set_router_high_water_mark(self, value: int):
        """Set the high-water mark applied to the node's router sockets."""
        ...
    def set_pubsub_high_water_mark(self, value: int):
        """Set the high-water mark applied to the node's pub/sub sockets."""
        ...
    def set_router_hwm_profile(self, value: int | AutoHwmProfile):
        """Set the auto-HWM profile for the node's router sockets."""
        ...
    def set_pubsub_hwm_profile(self, value: int | AutoHwmProfile):
        """Set the auto-HWM profile for the node's pub/sub sockets."""
        ...

    @property
    def router_hwm_profile(self):
        """The auto-HWM profile for the node's router sockets."""
        ...
    @router_hwm_profile.setter
    def router_hwm_profile(self, value): ...
    @property
    def router_high_water_mark(self):
        """The high-water mark applied to the node's router sockets."""
        ...
    @router_high_water_mark.setter
    def router_high_water_mark(self, value): ...
    @property
    def pubsub_hwm_profile(self):
        """The auto-HWM profile for the node's pub/sub sockets."""
        ...
    @pubsub_hwm_profile.setter
    def pubsub_hwm_profile(self, value): ...
    @property
    def pubsub_high_water_mark(self):
        """The high-water mark applied to the node's pub/sub sockets."""
        ...
    @pubsub_high_water_mark.setter
    def pubsub_high_water_mark(self, value): ...
    @property
    def dispatch_workers_min(self):
        """The minimum number of dispatch worker threads."""
        ...
    @dispatch_workers_min.setter
    def dispatch_workers_min(self, value: int): ...
    @property
    def dispatch_workers_max(self):
        """The maximum number of dispatch worker threads."""
        ...
    @dispatch_workers_max.setter
    def dispatch_workers_max(self, value: int): ...

    def create_spot(self):
        """Create a new user spot on the node. The caller owns it."""
        ...
    def entry_spot(self):
        """Return the node's entry spot."""
        ...
    def spot_lookup(self, spot_rid):
        """Look up a spot by routing id, or ``None`` when absent."""
        ...
    def get_or_create_spot(self, spot_rid):
        """Return the spot for ``spot_rid``, creating it if absent."""
        ...
    def actor(self, actor_id):
        """Create a local actor with id ``actor_id``. The caller owns it."""
        ...
    def actor_lookup(self, actor_id):
        """Look up a local actor by id, returning its reference."""
        ...
    def destroy_actor(self, actor_ref):
        """Begin destroying ``actor_ref``; submit the returned operation."""
        ...
    def remote_actor_get_ref(self, target_node_rid, actor_id):
        """Begin looking up a remote actor's reference; submit the returned operation."""
        ...
    def join_actor(self, actor_ref, dest_node_rid, dest_spot_rid):
        """Begin joining ``actor_ref`` to a spot on another node; submit the returned operation."""
        ...
    def join_actor_entry_spot(self, actor_ref, dest_node_rid, request):
        """Begin joining ``actor_ref`` to a node's entry spot with a request message."""
        ...
    def leave_actor(self, actor_ref, current_spot_rid):
        """Begin removing ``actor_ref`` from ``current_spot_rid``; submit the returned operation."""
        ...
    def send_bound_session_msg(self, actor_ref):
        """Begin a send to ``actor_ref``'s bound session; parts are consumed on a successful submit."""
        ...
    def spots(self):
        """Return the spots hosted on the node."""
        ...
    def actors(self):
        """Return the actors hosted on the node."""
        ...
    def set_routing_id(self, routing_id):
        """Set the node's routing id."""
        ...
    def get_routing_id(self):
        """Return the node's routing id."""
        ...
    @property
    def routing_id(self):
        """The node's routing id."""
        ...
    def set_tls_server(self, cert: str, key: str, require_client_cert: bool = False):
        """Configure the node as a TLS server; apply before binding."""
        ...
    def set_tls_client(
        self, ca_cert: str | None, hostname: str | None, trust_system: bool = False
    ): ...
    def status(self):
        """Return a snapshot of the node's status."""
        ...
    def peers(self):
        """Return the node's peers."""
        ...
    def peers_query(self, filter_=None):
        """Return the node's peers matching ``filter_``."""
        ...
    def subjects(self, filter_=None):
        """Return the node's subjects, optionally filtered."""
        ...
    def internal_sockets(self, filter_=None):
        """Return the node's internal sockets, optionally filtered."""
        ...

    def close(self, *args, **kwargs):
        """Close the node and release its resources."""
        ...

    def __enter__(self): ...

    def __exit__(self, exc_type, exc, tb): ...

    async def __aenter__(self): ...

    async def __aexit__(self, exc_type, exc, tb): ...


__all__ = ["SpotNode"]
