# SPDX-License-Identifier: MPL-2.0

from . import spot as _spot_contract


class _FluentMessageOp(metaclass=_spot_contract._SpotContractMeta):
    def message(self, payload): ...
    def messages(self, *payloads): ...
    def flags(self, flags): ...


class SendOp(_FluentMessageOp):
    def submit(self): ...


class RequestOp(_FluentMessageOp):
    def timeout(self, timeout): ...
    def submit_async(self): ...
    def submit(self, callback): ...


class RequestCallbackOp(_FluentMessageOp):
    def timeout(self, timeout): ...
    def submit(self, callback): ...


class ReplyOp(_FluentMessageOp):
    def submit(self): ...


class ActorJoinOp(_FluentMessageOp):
    def timeout(self, timeout): ...
    def submit_async(self): ...
    def submit(self, callback): ...


class ActorJoinCallbackOp(_FluentMessageOp):
    def timeout(self, timeout): ...
    def submit(self, callback): ...


class ActorJoinEntrySpotOp(metaclass=_spot_contract._SpotContractMeta):
    def timeout(self, timeout): ...
    def submit_async(self): ...
    def submit(self, callback): ...


class ActorJoinReplyOp(_FluentMessageOp):
    def submit(self): ...


class ActorLeaveOp(metaclass=_spot_contract._SpotContractMeta):
    def timeout(self, timeout): ...
    def submit_async(self): ...
    def submit(self, callback): ...


class ActorDestroyOp(ActorLeaveOp): ...


class ActorLookupOp(metaclass=_spot_contract._SpotContractMeta):
    def timeout(self, timeout): ...
    def submit_async(self): ...
    def submit(self, callback): ...


class ActorBindOp(ActorLeaveOp): ...


class ActorUnbindOp(ActorLeaveOp): ...


__all__ = [
    "ActorBindOp",
    "ActorDestroyOp",
    "ActorJoinCallbackOp",
    "ActorJoinEntrySpotOp",
    "ActorJoinOp",
    "ActorJoinReplyOp",
    "ActorLeaveOp",
    "ActorLookupOp",
    "ActorUnbindOp",
    "ReplyOp",
    "RequestCallbackOp",
    "RequestOp",
    "SendOp",
]
