[package]
name = "zlink-codec-json"
version = "6.0.0"
edition = "2024"
rust-version = "1.85"
description = "JSON codec extension for the zlink Rust bindings"
license = "MPL-2.0"
homepage = "https://zlink.systems/"

[dependencies]
serde = "1"
serde_json = "1"
zlink = { version = "6.0.0", path = "../.." }

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
