<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>PubSub.Server.Shared</AssemblyName>
    <RootNamespace>PubSub.Server</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../Shared/PubSub.Shared.csproj" />
    <ProjectReference Include="../../../../src/Zlink.Framework/Zlink.Framework.csproj" />
  </ItemGroup>
</Project>
