# SPDX-License-Identifier: MPL-2.0

from typing import Protocol, runtime_checkable

from . import socket as _socket_contract


@runtime_checkable
class PubSocket(_socket_contract._SocketContract, Protocol):
    @property
    def pub_options(self): ...

    def connect(self, endpoint): ...

    def disconnect(self, endpoint): ...

    def publish(self, topic): ...


@runtime_checkable
class SubSocket(_socket_contract._SocketContract, Protocol):
    @property
    def sub_options(self): ...

    def connect(self, endpoint): ...

    def disconnect(self, endpoint): ...

    def set_subscription(self, topic): ...

    def unset_subscription(self, topic): ...

    def subscribe_into(self, topic_message, *, flags=0): ...


@runtime_checkable
class XPubSocket(_socket_contract._SocketContract, Protocol):
    @property
    def pub_options(self): ...

    def connect(self, endpoint): ...

    def disconnect(self, endpoint): ...

    def publish(self, topic): ...

    def receive_subscription_event_into(self, event, *, flags=0): ...


@runtime_checkable
class XSubSocket(_socket_contract._SocketContract, Protocol):
    @property
    def sub_options(self): ...

    def connect(self, endpoint): ...

    def disconnect(self, endpoint): ...

    def set_subscription(self, topic): ...

    def unset_subscription(self, topic): ...

    def subscribe_into(self, topic_message, *, flags=0): ...


__all__ = ["PubSocket", "SubSocket", "XPubSocket", "XSubSocket"]
