# SPDX-License-Identifier: MPL-2.0

from typing import Protocol, runtime_checkable

from . import socket as _socket_contract


@runtime_checkable
class RouterSocket(_socket_contract._SocketContract, Protocol):
    @property
    def router_options(self): ...

    def connect(self, endpoint): ...

    def disconnect(self, endpoint): ...

    def send(self, routing_id): ...

    def request(self, routing_id): ...

    def reply(self, routing_id, request_seq): ...

    def recv_into(self, received, *, flags=0): ...

    def send_to_spot(self, node_rid, spot_rid): ...

    def request_to_spot(self, node_rid, spot_rid): ...

    def reply_to_spot(self, node_rid, spot_rid, request_seq): ...


__all__ = ["RouterSocket"]
