# SPDX-License-Identifier: MPL-2.0

from typing import Protocol, runtime_checkable

from . import socket as _socket_contract


@runtime_checkable
class StreamSocket(_socket_contract._SocketContract, Protocol):
    @property
    def stream_options(self): ...

    def send(self, routing_id): ...

    def recv_into(self, received, *, flags=0): ...

    def attach_actor_gateway(self, node): ...

    def bind_actor(self, session_id, actor_id, *, callback=None): ...

    def unbind_actor(self, session_id, actor_id, *, callback=None): ...

    def send_bound_actor(self, session_id, actor_id): ...

    def bound_actors(self, session_id): ...

    def on_packet(self, handler): ...

    def disconnect_rid(self, peer_rid): ...


__all__ = ["StreamSocket"]
