# SPDX-License-Identifier: MPL-2.0

from typing import Protocol, runtime_checkable

_context_factory = None


def register_context_factory(factory):
    global _context_factory
    _context_factory = factory


def create_context():
    if _context_factory is None:
        raise RuntimeError("zlink context runtime is not registered")
    return _context_factory()


@runtime_checkable
class Context(Protocol):
    @property
    def options(self): ...

    def recalculate_auto_hwm(self): ...

    def shutdown(self): ...

    def close(self): ...

    def __enter__(self): ...

    def __exit__(self, exc_type, exc, tb): ...

    async def __aenter__(self): ...

    async def __aexit__(self, exc_type, exc, tb): ...


@runtime_checkable
class ContextOptions(Protocol):
    @property
    def io_threads(self): ...
    @io_threads.setter
    def io_threads(self, value): ...

    @property
    def max_sockets(self): ...
    @max_sockets.setter
    def max_sockets(self, value): ...

    @property
    def max_message_size(self): ...
    @max_message_size.setter
    def max_message_size(self, value): ...

    @property
    def thread_priority(self): ...
    @thread_priority.setter
    def thread_priority(self, value): ...

    @property
    def thread_scheduling_policy(self): ...
    @thread_scheduling_policy.setter
    def thread_scheduling_policy(self, value): ...

    @property
    def thread_name_prefix(self): ...
    @thread_name_prefix.setter
    def thread_name_prefix(self, value): ...

    @property
    def auto_hwm_enabled(self): ...
    @auto_hwm_enabled.setter
    def auto_hwm_enabled(self, value): ...

    @property
    def auto_hwm_recalc_debounce(self): ...
    @auto_hwm_recalc_debounce.setter
    def auto_hwm_recalc_debounce(self, value): ...

    @property
    def blocky(self): ...
    @blocky.setter
    def blocky(self, value): ...

    @property
    def auto_hwm_profile(self): ...
    @auto_hwm_profile.setter
    def auto_hwm_profile(self, value): ...

    @property
    def auto_hwm_msg_unit_bytes(self): ...
    @auto_hwm_msg_unit_bytes.setter
    def auto_hwm_msg_unit_bytes(self, value): ...

    @property
    def socket_limit(self): ...

    @property
    def msg_t_size(self): ...

    def add_thread_affinity(self, cpu): ...

    def remove_thread_affinity(self, cpu): ...
