/* SPDX-License-Identifier: MPL-2.0 */

#include "addon_api.h"

static napi_value init(napi_env env, napi_value exports)
{
    napi_property_descriptor descs[] = {
        {"version", 0, version, 0, 0, 0, napi_default, 0},
        {"ctxNew", 0, ctx_new, 0, 0, 0, napi_default, 0},
        {"ctxTerm", 0, ctx_term, 0, 0, 0, napi_default, 0},
        {"socketNew", 0, socket_new, 0, 0, 0, napi_default, 0},
        {"socketClose", 0, socket_close, 0, 0, 0, napi_default, 0},
        {"socketBind", 0, socket_bind, 0, 0, 0, napi_default, 0},
        {"socketConnect", 0, socket_connect, 0, 0, 0, napi_default, 0},
        {"socketSend", 0, socket_send, 0, 0, 0, napi_default, 0},
        {"socketSendParts", 0, socket_send_parts, 0, 0, 0, napi_default, 0},
        {"socketPublish", 0, socket_publish, 0, 0, 0, napi_default, 0},
        {"socketTryPublish", 0, socket_try_publish, 0, 0, 0, napi_default, 0},
        {"socketTrySend", 0, socket_try_send, 0, 0, 0, napi_default, 0},
        {"socketTrySendParts", 0, socket_try_send_parts, 0, 0, 0, napi_default, 0},
        {"socketTrySendRouting", 0, socket_try_send_routing, 0, 0, 0, napi_default, 0},
        {"socketTrySendRoutingParts", 0, socket_try_send_routing_parts, 0, 0, 0, napi_default, 0},
        {"socketSendFrom", 0, socket_send_from, 0, 0, 0, napi_default, 0},
        {"socketRecv", 0, socket_recv, 0, 0, 0, napi_default, 0},
        {"socketRecvMessage", 0, socket_recv_message, 0, 0, 0, napi_default, 0},
        {"socketTryRecvMessage", 0, socket_try_recv_message, 0, 0, 0, napi_default, 0},
        {"socketRecvHandler", 0, socket_recv_handler, 0, 0, 0, napi_default, 0},
        {"socketSubscribeMessage", 0, socket_subscribe_message, 0, 0, 0, napi_default, 0},
        {"socketTrySubscribeMessage", 0, socket_try_subscribe_message, 0, 0, 0, napi_default, 0},
        {"socketSubscribeHandler", 0, socket_subscribe_handler, 0, 0, 0, napi_default, 0},
        {"socketSubscriptionEvent", 0, socket_subscription_event, 0, 0, 0, napi_default, 0},
        {"socketTrySubscriptionEvent", 0, socket_try_subscription_event, 0, 0, 0, napi_default, 0},
        {"socketRecvInto", 0, socket_recv_into, 0, 0, 0, napi_default, 0},
        {"socketRecvMsgInto", 0, socket_recv_msg_into, 0, 0, 0, napi_default, 0},
        {"socketStreamAttach", 0, socket_stream_attach, 0, 0, 0, napi_default, 0},
        {"socketStreamDetach", 0, socket_stream_detach, 0, 0, 0, napi_default, 0},
        {"socketStreamPeerRoutingId", 0, socket_stream_peer_routing_id, 0, 0, 0, napi_default, 0},
        {"socketStreamSend", 0, socket_stream_send, 0, 0, 0, napi_default, 0},
        {"socketSetOpt", 0, socket_setopt, 0, 0, 0, napi_default, 0},
        {"socketGetOpt", 0, socket_getopt, 0, 0, 0, napi_default, 0},

        {"registryNew", 0, registry_new, 0, 0, 0, napi_default, 0},
        {"registrySetEndpoints", 0, registry_set_endpoints, 0, 0, 0, napi_default, 0},
        {"registrySetId", 0, registry_set_id, 0, 0, 0, napi_default, 0},
        {"registryAddPeer", 0, registry_add_peer, 0, 0, 0, napi_default, 0},
        {"registrySetHeartbeat", 0, registry_set_heartbeat, 0, 0, 0, napi_default, 0},
        {"registrySetBroadcastInterval", 0, registry_set_broadcast, 0, 0, 0, napi_default, 0},
        {"registryStart", 0, registry_start, 0, 0, 0, napi_default, 0},
        {"registrySetSockOpt", 0, registry_setsockopt, 0, 0, 0, napi_default, 0},
        {"registryStatusSnapshot", 0, registry_status_snapshot, 0, 0, 0, napi_default, 0},
        {"registryServiceSummarySnapshot", 0, registry_service_summary_snapshot, 0, 0, 0, napi_default, 0},
        {"registryTopologySnapshot", 0, registry_topology_snapshot, 0, 0, 0, napi_default, 0},
        {"registryTopologyQuery", 0, registry_topology_query, 0, 0, 0, napi_default, 0},
        {"registryMemberPeers", 0, registry_member_peers, 0, 0, 0, napi_default, 0},
        {"registryQueryClientNew", 0, registry_query_client_new, 0, 0, 0, napi_default, 0},
        {"registryQueryClientConnect", 0, registry_query_client_connect, 0, 0, 0, napi_default, 0},
        {"registryQuerySnapshot", 0, registry_query_snapshot, 0, 0, 0, napi_default, 0},
        {"registryQueryDestroy", 0, registry_query_destroy, 0, 0, 0, napi_default, 0},
        {"registryDestroy", 0, registry_destroy, 0, 0, 0, napi_default, 0},

        {"discoveryNew", 0, discovery_new, 0, 0, 0, napi_default, 0},
        {"discoveryConnectRegistry", 0, discovery_connect, 0, 0, 0, napi_default, 0},
        {"discoveryProviderCount", 0, discovery_provider_count, 0, 0, 0, napi_default, 0},
        {"discoveryServiceAvailable", 0, discovery_service_available, 0, 0, 0, napi_default, 0},
        {"discoveryGetProviders", 0, discovery_get_providers, 0, 0, 0, napi_default, 0},
        {"discoveryOpenMonitor", 0, discovery_open_monitor, 0, 0, 0, napi_default, 0},
        {"serviceMonitorRecv", 0, service_monitor_recv, 0, 0, 0, napi_default, 0},
        {"serviceMonitorTryRecv", 0, service_monitor_try_recv, 0, 0, 0, napi_default, 0},
        {"discoverySetValue", 0, discovery_set_value, 0, 0, 0, napi_default, 0},
        {"discoveryGetValue", 0, discovery_get_value, 0, 0, 0, napi_default, 0},
        {"discoverySetMetadata", 0, discovery_set_metadata, 0, 0, 0, napi_default, 0},
        {"discoveryGetMetadata", 0, discovery_get_metadata, 0, 0, 0, napi_default, 0},
        {"discoverySetTlsClient", 0, discovery_set_tls_client, 0, 0, 0, napi_default, 0},
        {"discoveryDestroy", 0, discovery_destroy, 0, 0, 0, napi_default, 0},

        {"providerNew", 0, provider_new, 0, 0, 0, napi_default, 0},
        {"providerBind", 0, provider_bind, 0, 0, 0, napi_default, 0},
        {"providerConnectRegistry", 0, provider_connect_registry, 0, 0, 0, napi_default, 0},
        {"providerRegister", 0, provider_register, 0, 0, 0, napi_default, 0},
        {"providerUpdateWeight", 0, provider_update_weight, 0, 0, 0, napi_default, 0},
        {"providerUnregister", 0, provider_unregister, 0, 0, 0, napi_default, 0},
        {"providerRegisterResult", 0, provider_register_result, 0, 0, 0, napi_default, 0},
        {"providerSetTlsServer", 0, provider_set_tls_server, 0, 0, 0, napi_default, 0},
        {"providerRouter", 0, provider_router, 0, 0, 0, napi_default, 0},
        {"providerRouterPeers", 0, provider_router_peers, 0, 0, 0, napi_default, 0},
        {"providerSetSockOpt", 0, provider_setsockopt, 0, 0, 0, napi_default, 0},
        {"providerDestroy", 0, provider_destroy, 0, 0, 0, napi_default, 0},

        {"spotNodeNew", 0, spot_node_new, 0, 0, 0, napi_default, 0},
        {"spotNodeDestroy", 0, spot_node_destroy, 0, 0, 0, napi_default, 0},
        {"spotNodeBind", 0, spot_node_bind, 0, 0, 0, napi_default, 0},
        {"spotNodeConnectPeerPub", 0, spot_node_connect_peer, 0, 0, 0, napi_default, 0},
        {"spotNodeDisconnectPeerPub", 0, spot_node_disconnect_peer, 0, 0, 0, napi_default, 0},
        {"spotNodeRegister", 0, spot_node_register, 0, 0, 0, napi_default, 0},
        {"spotNodeUnregister", 0, spot_node_unregister, 0, 0, 0, napi_default, 0},
        {"spotNodeSetDiscovery", 0, spot_node_set_discovery, 0, 0, 0, napi_default, 0},
        {"spotNodeSetTlsServer", 0, spot_node_set_tls_server, 0, 0, 0, napi_default, 0},
        {"spotNodeSetTlsClient", 0, spot_node_set_tls_client, 0, 0, 0, napi_default, 0},
        {"spotNodeSetSockOpt", 0, spot_node_setsockopt, 0, 0, 0, napi_default, 0},
        {"spotNodeOpenMonitor", 0, spot_node_open_monitor, 0, 0, 0, napi_default, 0},
        {"spotNodeStatusSnapshot", 0, spot_node_status_snapshot, 0, 0, 0, napi_default, 0},
        {"spotNodePeersSnapshot", 0, spot_node_peers_snapshot, 0, 0, 0, napi_default, 0},
        {"spotNodeSubjectsSnapshot", 0, spot_node_subjects_snapshot, 0, 0, 0, napi_default, 0},
        {"spotNodePubSocket", 0, spot_node_pub_socket, 0, 0, 0, napi_default, 0},
        {"spotNodeSubSocket", 0, spot_node_sub_socket, 0, 0, 0, napi_default, 0},
        {"spotNodePubPeers", 0, spot_node_pub_peers, 0, 0, 0, napi_default, 0},
        {"spotNodeSubPeers", 0, spot_node_sub_peers, 0, 0, 0, napi_default, 0},

        {"spotNew", 0, spot_new, 0, 0, 0, napi_default, 0},
        {"spotDestroy", 0, spot_destroy, 0, 0, 0, napi_default, 0},
        {"spotPublish", 0, spot_publish, 0, 0, 0, napi_default, 0},
        {"spotTryPublish", 0, spot_try_publish, 0, 0, 0, napi_default, 0},
        {"spotEnableSendReadyNoop", 0, spot_enable_send_ready_noop, 0, 0, 0,
         napi_default, 0},
        {"spotSubscribe", 0, spot_subscribe, 0, 0, 0, napi_default, 0},
        {"spotSubscribePattern", 0, spot_subscribe_pattern, 0, 0, 0, napi_default, 0},
        {"spotUnsubscribe", 0, spot_unsubscribe, 0, 0, 0, napi_default, 0},
        {"spotRecv", 0, spot_recv, 0, 0, 0, napi_default, 0},
        {"spotTryRecv", 0, spot_try_recv, 0, 0, 0, napi_default, 0},
        {"spotSubscribeHandler", 0, spot_subscribe_handler, 0, 0, 0, napi_default, 0},
        {"spotOpenMonitor", 0, spot_open_monitor, 0, 0, 0, napi_default, 0},
        {"monitorOpen", 0, monitor_open, 0, 0, 0, napi_default, 0},
        {"monitorRecv", 0, monitor_recv, 0, 0, 0, napi_default, 0},
        {"monitorTryRecv", 0, monitor_try_recv, 0, 0, 0, napi_default, 0},
        {"monitorSnapshot", 0, monitor_snapshot, 0, 0, 0, napi_default, 0},
        {"monitorClose", 0, monitor_close, 0, 0, 0, napi_default, 0},

        {"poll", 0, poll, 0, 0, 0, napi_default, 0},
    };

    napi_define_properties(env, exports, sizeof(descs) / sizeof(*descs), descs);
    return exports;
}

NAPI_MODULE(NODE_GYP_MODULE_NAME, init)
