/* SPDX-License-Identifier: MPL-2.0 */

#include "addon_core_api.h"
#include "addon_discovery_api.h"
#include "addon_spot_api.h"

#define ZLINK_METHOD(js_name, native_fn) \
    { js_name, 0, native_fn, 0, 0, 0, napi_default, 0 }

static void define_exports(napi_env env,
                           napi_value exports,
                           napi_property_descriptor *descs,
                           size_t count)
{
    napi_define_properties(env, exports, count, descs);
}

static void define_core_exports(napi_env env, napi_value exports)
{
    napi_property_descriptor descs[] = {
        ZLINK_METHOD("version", version),
        ZLINK_METHOD("ctxNew", ctx_new),
        ZLINK_METHOD("ctxShutdown", ctx_shutdown),
        ZLINK_METHOD("ctxTerm", ctx_term),
        ZLINK_METHOD("ctxSetOpt", ctx_setopt),
        ZLINK_METHOD("ctxGetOpt", ctx_getopt),
        ZLINK_METHOD("ctxRecalculateAutoHwm", ctx_recalculate_auto_hwm),
        ZLINK_METHOD("socketNew", socket_new),
        ZLINK_METHOD("socketClose", socket_close),
        ZLINK_METHOD("socketBind", socket_bind),
        ZLINK_METHOD("socketUnbind", socket_unbind),
        ZLINK_METHOD("socketConnect", socket_connect),
        ZLINK_METHOD("socketDisconnect", socket_disconnect),
        ZLINK_METHOD("socketDisconnectRid", socket_disconnect_rid),
        ZLINK_METHOD("socketSetTlsServer", socket_set_tls_server),
        ZLINK_METHOD("socketSetTlsClient", socket_set_tls_client),
        ZLINK_METHOD("socketAttachDiscovery", socket_attach_discovery),
        ZLINK_METHOD("socketSend", socket_send),
        ZLINK_METHOD("socketSendParts", socket_send_parts),
        ZLINK_METHOD("socketPublish", socket_publish),
        ZLINK_METHOD("socketTryPublish", socket_try_publish),
        ZLINK_METHOD("socketSendNoWaitResult", socket_try_send),
        ZLINK_METHOD("socketSendNoWaitResultParts", socket_try_send_parts),
        ZLINK_METHOD("socketSendRoutingNoWaitResult", socket_try_send_routing),
        ZLINK_METHOD("socketSendRoutingNoWaitResultParts", socket_try_send_routing_parts),
        ZLINK_METHOD("socketSendRouting", socket_send_routing),
        ZLINK_METHOD("socketPerfDealerDealerSendLoop", socket_perf_dealer_dealer_send_loop),
        ZLINK_METHOD("socketPerfDealerRouterEchoLoop", socket_perf_dealer_router_echo_loop),
        ZLINK_METHOD("socketSendFrom", socket_send_from),
        ZLINK_METHOD("socketRecv", socket_recv),
        ZLINK_METHOD("socketRecvMessage", socket_recv_message),
        ZLINK_METHOD("socketRecvMessageNoWait", socket_try_recv_message),
        ZLINK_METHOD("socketRecvHandler", socket_recv_handler),
        ZLINK_METHOD("socketSubscribeMessage", socket_subscribe_message),
        ZLINK_METHOD("socketTrySubscribeMessage", socket_try_subscribe_message),
        ZLINK_METHOD("socketSubscribePayloadInto", socket_subscribe_payload_into),
        ZLINK_METHOD("socketSubscribeHandler", socket_subscribe_handler),
        ZLINK_METHOD("socketSendReadyHandler", socket_send_ready_handler),
        ZLINK_METHOD("socketSubscriptionEvent", socket_subscription_event),
        ZLINK_METHOD("socketTrySubscriptionEvent", socket_try_subscription_event),
        ZLINK_METHOD("subscriptionAt", subscription_at),
        ZLINK_METHOD("socketRecvInto", socket_recv_into),
        ZLINK_METHOD("socketRecvMsgInto", socket_recv_msg_into),
        ZLINK_METHOD("socketStreamAttach", socket_stream_attach),
        ZLINK_METHOD("socketStreamAttachPacketEcho", socket_stream_attach_packet_echo),
        ZLINK_METHOD("socketRouteEchoStep", socket_route_echo_step),
        ZLINK_METHOD("socketStreamDetach", socket_stream_detach),
        ZLINK_METHOD("socketStreamPeerRoutingId", socket_stream_peer_routing_id),
        ZLINK_METHOD("socketStreamSend", socket_stream_send),
        ZLINK_METHOD("streamBindActor", stream_bind_actor),
        ZLINK_METHOD("streamUnbindActor", stream_unbind_actor),
        ZLINK_METHOD("streamSendBoundActorPart", stream_send_bound_actor_part),
        ZLINK_METHOD("socketSetOpt", socket_setopt),
        ZLINK_METHOD("socketGetOpt", socket_getopt),
        ZLINK_METHOD("socketSetChannelName", socket_set_channel_name),
        ZLINK_METHOD("socketGetChannelName", socket_get_channel_name),
        ZLINK_METHOD("handleSetRoutingId", handle_set_routing_id),
        ZLINK_METHOD("handleGetRoutingId", handle_get_routing_id),
        ZLINK_METHOD("dealerRequest", dealer_request),
        ZLINK_METHOD("routerRequest", router_request),
        ZLINK_METHOD("routerReply", router_reply),
        ZLINK_METHOD("routerHandlerMessage", router_handler_message),
        ZLINK_METHOD("routerRecvMessage", router_recv_message),
        ZLINK_METHOD("routerRecvMessageNoWait", router_try_recv_message),
        ZLINK_METHOD("routerRecvInto", router_recv_into),
        ZLINK_METHOD("routerRecvPayloadInto", router_recv_payload_into),
        ZLINK_METHOD("routerSpotSend", router_spot_send),
        ZLINK_METHOD("routerSpotRequest", router_spot_request),
        ZLINK_METHOD("routerSpotReply", router_spot_reply),
        ZLINK_METHOD("monitorOpen", monitor_open),
        ZLINK_METHOD("monitorHandler", monitor_handler),
        ZLINK_METHOD("monitorRecv", monitor_recv),
        ZLINK_METHOD("monitorRecvNoWait", monitor_try_recv),
        ZLINK_METHOD("monitorSnapshot", monitor_snapshot),
        ZLINK_METHOD("monitorClose", monitor_close),
        ZLINK_METHOD("pollerNew", poller_new),
        ZLINK_METHOD("pollerDestroy", poller_destroy),
        ZLINK_METHOD("pollerSize", poller_size),
        ZLINK_METHOD("pollerAdd", poller_add),
        ZLINK_METHOD("pollerModify", poller_modify),
        ZLINK_METHOD("pollerRemove", poller_remove),
        ZLINK_METHOD("pollerAddFd", poller_add_fd),
        ZLINK_METHOD("pollerModifyFd", poller_modify_fd),
        ZLINK_METHOD("pollerRemoveFd", poller_remove_fd),
        ZLINK_METHOD("pollerAddTimer", poller_add_timer),
        ZLINK_METHOD("pollerRemoveTimer", poller_remove_timer),
        ZLINK_METHOD("pollerWait", poller_wait),
        ZLINK_METHOD("pollerWaitMany", poller_wait_many),
        ZLINK_METHOD("pollEventsNew", poll_events_new),
        ZLINK_METHOD("pollEventsDestroy", poll_events_destroy),
        ZLINK_METHOD("pollEventsSourceKind", poll_events_source_kind),
        ZLINK_METHOD("pollEventsSlot", poll_events_slot),
        ZLINK_METHOD("pollEventsRevents", poll_events_revents),
        ZLINK_METHOD("pollEventsFd", poll_events_fd),
        ZLINK_METHOD("pollerWaitInto", poller_wait_into),
        ZLINK_METHOD("timerNew", timer_new),
        ZLINK_METHOD("spotTimerNew", spot_timer_new),
        ZLINK_METHOD("timerDestroy", timer_destroy),
        ZLINK_METHOD("timerStart", timer_start),
        ZLINK_METHOD("timerStop", timer_stop),
        ZLINK_METHOD("timerRecv", timer_recv),
        ZLINK_METHOD("timerHandler", timer_handler),
        ZLINK_METHOD("stopwatchStart", stopwatch_start),
        ZLINK_METHOD("stopwatchIntermediate", stopwatch_intermediate),
        ZLINK_METHOD("stopwatchStop", stopwatch_stop),
        ZLINK_METHOD("atomicCounterNew", atomic_counter_new),
        ZLINK_METHOD("atomicCounterSet", atomic_counter_set),
        ZLINK_METHOD("atomicCounterInc", atomic_counter_inc),
        ZLINK_METHOD("atomicCounterDec", atomic_counter_dec),
        ZLINK_METHOD("atomicCounterValue", atomic_counter_value),
        ZLINK_METHOD("atomicCounterDestroy", atomic_counter_destroy),
        ZLINK_METHOD("poll", poll),
    };
    define_exports(env, exports, descs, sizeof(descs) / sizeof(*descs));
}

static void define_discovery_exports(napi_env env, napi_value exports)
{
    napi_property_descriptor descs[] = {
        ZLINK_METHOD("registryNew", registry_new),
        ZLINK_METHOD("registrySetEndpoints", registry_set_endpoints),
        ZLINK_METHOD("registrySetId", registry_set_id),
        ZLINK_METHOD("registryAddPeer", registry_add_peer),
        ZLINK_METHOD("registrySetHeartbeat", registry_set_heartbeat),
        ZLINK_METHOD("registrySetBroadcastInterval", registry_set_broadcast),
        ZLINK_METHOD("registrySetTlsServer", registry_set_tls_server),
        ZLINK_METHOD("registrySetTlsClient", registry_set_tls_client),
        ZLINK_METHOD("registryStart", registry_start),
        ZLINK_METHOD("registrySetSockOpt", registry_setsockopt),
        ZLINK_METHOD("registryStatusSnapshot", registry_status_snapshot),
        ZLINK_METHOD("registryServiceSummarySnapshot", registry_service_summary_snapshot),
        ZLINK_METHOD("registryTopologySnapshot", registry_topology_snapshot),
        ZLINK_METHOD("registryTopologyQuery", registry_topology_query),
        ZLINK_METHOD("registryMemberPeers", registry_member_peers),
        ZLINK_METHOD("registryQueryClientNew", registry_query_client_new),
        ZLINK_METHOD("registryQueryClientConnect", registry_query_client_connect),
        ZLINK_METHOD("registryQuerySnapshot", registry_query_snapshot),
        ZLINK_METHOD("registryQueryDestroy", registry_query_destroy),
        ZLINK_METHOD("registryDestroy", registry_destroy),
        ZLINK_METHOD("discoveryNew", discovery_new),
        ZLINK_METHOD("discoveryConnectRegistry", discovery_connect),
        ZLINK_METHOD("discoveryProviderCount", discovery_provider_count),
        ZLINK_METHOD("discoveryServiceAvailable", discovery_service_available),
        ZLINK_METHOD("discoveryGetProviders", discovery_get_providers),
        ZLINK_METHOD("discoverySetValue", discovery_set_value),
        ZLINK_METHOD("discoveryGetValue", discovery_get_value),
        ZLINK_METHOD("discoveryResolveSpot", discovery_resolve_spot),
        ZLINK_METHOD("discoveryResolveActor", discovery_resolve_actor),
        ZLINK_METHOD("discoverySetTlsClient", discovery_set_tls_client),
        ZLINK_METHOD("discoveryDestroy", discovery_destroy),
        ZLINK_METHOD("providerNew", provider_new),
        ZLINK_METHOD("providerBind", provider_bind),
        ZLINK_METHOD("providerConnectRegistry", provider_connect_registry),
        ZLINK_METHOD("providerRegister", provider_register),
        ZLINK_METHOD("providerUpdateWeight", provider_update_weight),
        ZLINK_METHOD("providerUnregister", provider_unregister),
        ZLINK_METHOD("providerRegisterResult", provider_register_result),
        ZLINK_METHOD("providerSetTlsServer", provider_set_tls_server),
        ZLINK_METHOD("providerRouter", provider_router),
        ZLINK_METHOD("providerRouterPeers", provider_router_peers),
        ZLINK_METHOD("providerSetSockOpt", provider_setsockopt),
        ZLINK_METHOD("providerDestroy", provider_destroy),
    };
    define_exports(env, exports, descs, sizeof(descs) / sizeof(*descs));
}

static void define_spot_exports(napi_env env, napi_value exports)
{
    napi_property_descriptor descs[] = {
        ZLINK_METHOD("spotNodeNew", spot_node_new),
        ZLINK_METHOD("spotNodeDestroy", spot_node_destroy),
        ZLINK_METHOD("spotNodeBind", spot_node_bind),
        ZLINK_METHOD("spotNodeConnectPeerPub", spot_node_connect_peer),
        ZLINK_METHOD("spotNodeDisconnectPeerPub", spot_node_disconnect_peer),
        ZLINK_METHOD("spotNodeDisconnectPeerRidPub", spot_node_disconnect_peer_rid),
        ZLINK_METHOD("spotNodeConnectRouterChannelPeer", spot_node_connect_router_channel_peer),
        ZLINK_METHOD("spotNodeDisconnectRouterChannelPeer", spot_node_disconnect_router_channel_peer),
        ZLINK_METHOD("spotNodeDisconnectRouterChannelPeerRid", spot_node_disconnect_router_channel_peer_rid),
        ZLINK_METHOD("spotNodeRegister", spot_node_register),
        ZLINK_METHOD("spotNodeUnregister", spot_node_unregister),
        ZLINK_METHOD("spotNodeSetDiscovery", spot_node_set_discovery),
        ZLINK_METHOD("spotNodeAttachRouterChannelDiscovery", spot_node_attach_router_channel_discovery),
        ZLINK_METHOD("spotNodeAttachChannelDealer", spot_node_attach_channel_dealer),
        ZLINK_METHOD("spotNodeAttachChannelDealerManual", spot_node_attach_channel_dealer_manual),
        ZLINK_METHOD("spotNodeAttachPubIngress", spot_node_attach_pub_ingress),
        ZLINK_METHOD("spotNodeSetTlsServer", spot_node_set_tls_server),
        ZLINK_METHOD("spotNodeSetTlsClient", spot_node_set_tls_client),
        ZLINK_METHOD("spotNodeSetOption", spot_node_setsockopt),
        ZLINK_METHOD("spotNodeGetOption", spot_node_getsockopt),
        ZLINK_METHOD("spotNodeEntrySpot", spot_node_entry_spot),
        ZLINK_METHOD("spotNodeSpotLookup", spot_node_spot_lookup),
        ZLINK_METHOD("spotNodeSpotGetOrNew", spot_node_spot_get_or_new),
        ZLINK_METHOD("spotNodeStatusSnapshot", spot_node_status_snapshot),
        ZLINK_METHOD("spotNodePeersSnapshot", spot_node_peers_snapshot),
        ZLINK_METHOD("spotNodePeersQuery", spot_node_peers_query),
        ZLINK_METHOD("spotNodeSubjectsSnapshot", spot_node_subjects_snapshot),
        ZLINK_METHOD("spotNodeInternalSocketsSnapshot", spot_node_internal_sockets_snapshot),
        ZLINK_METHOD("spotNodeSpotsSnapshot", spot_node_spots_snapshot),
        ZLINK_METHOD("spotNodeActorsSnapshot", spot_node_actors_snapshot),
        ZLINK_METHOD("spotNodePubSocket", spot_node_pub_socket),
        ZLINK_METHOD("spotNodeSubSocket", spot_node_sub_socket),
        ZLINK_METHOD("spotNodePubPeers", spot_node_pub_peers),
        ZLINK_METHOD("spotNodeSubPeers", spot_node_sub_peers),
        ZLINK_METHOD("spotNodeActorNew", spot_node_actor_new),
        ZLINK_METHOD("spotNodeActorDestroy", spot_node_actor_destroy),
        ZLINK_METHOD("spotNodeActorLookup", spot_node_actor_lookup),
        ZLINK_METHOD("spotNodeActorJoinSpot", spot_node_actor_join_spot),
        ZLINK_METHOD("spotNodeActorLeaveSpot", spot_node_actor_leave_spot),
        ZLINK_METHOD("spotNodeActorRecvPart", spot_node_actor_recv_part),
        ZLINK_METHOD("spotNodeActorSendBoundSessionMsg", spot_node_actor_send_bound_session_msg),
        ZLINK_METHOD("spotNodeActorCloseBoundSession", spot_node_actor_close_bound_session),
        ZLINK_METHOD("spotNew", spot_new),
        ZLINK_METHOD("spotDestroy", spot_destroy),
        ZLINK_METHOD("spotPublish", spot_publish),
        ZLINK_METHOD("spotTryPublish", spot_try_publish),
        ZLINK_METHOD("spotSendChannel", spot_send_channel),
        ZLINK_METHOD("spotSendToSpot", spot_send_spot),
        ZLINK_METHOD("spotSendToSpotFrom", spot_send_spot_from),
        ZLINK_METHOD("spotRequestChannel", spot_request_channel),
        ZLINK_METHOD("spotRequestSpot", spot_request_spot),
        ZLINK_METHOD("spotRequestSpotFrom", spot_request_spot_from),
        ZLINK_METHOD("spotRequestRouter", spot_request_router),
        ZLINK_METHOD("spotSetOption", spot_set_option),
        ZLINK_METHOD("spotGetOption", spot_get_option),
        ZLINK_METHOD("spotReplySpot", spot_reply_spot),
        ZLINK_METHOD("spotReplyRouter", spot_reply_router),
        ZLINK_METHOD("spotRoutedHandler", spot_routed_handler),
        ZLINK_METHOD("spotDispatchEventHandler", spot_dispatch_event_handler),
        ZLINK_METHOD("spotAttachRouteEcho", spot_attach_route_echo),
        ZLINK_METHOD("spotPerfSendSendLoop", spot_perf_sendsend_loop),
        ZLINK_METHOD("spotRecvRouted", spot_recv_routed),
        ZLINK_METHOD("spotRecvRoutedPayloadInto", spot_recv_routed_payload_into),
        ZLINK_METHOD("spotActorJoinRecv", spot_actor_join_recv),
        ZLINK_METHOD("spotActorJoinReply", spot_actor_join_reply),
        ZLINK_METHOD("spotActorsSnapshot", spot_actors_snapshot),
        ZLINK_METHOD("spotSendReadyHandler", spot_send_ready_handler),
        ZLINK_METHOD("spotSubscribe", spot_subscribe),
        ZLINK_METHOD("spotSubscribePattern", spot_subscribe_pattern),
        ZLINK_METHOD("spotUnsubscribe", spot_unsubscribe),
        ZLINK_METHOD("spotRecv", spot_recv),
        ZLINK_METHOD("spotRecvNoWait", spot_try_recv),
        ZLINK_METHOD("spotRecvPayloadInto", spot_recv_payload_into),
        ZLINK_METHOD("spotSubscriptionEvent", spot_subscription_event),
        ZLINK_METHOD("spotSubscriptionEventNoWait", spot_try_subscription_event),
        ZLINK_METHOD("spotSubscribeHandler", spot_subscribe_handler),
    };
    define_exports(env, exports, descs, sizeof(descs) / sizeof(*descs));
}

static napi_value init(napi_env env, napi_value exports)
{
    define_core_exports(env, exports);
    define_discovery_exports(env, exports);
    define_spot_exports(env, exports);
    return exports;
}

NAPI_MODULE(NODE_GYP_MODULE_NAME, init)
