/* SPDX-License-Identifier: MPL-2.0 */

#include "addon_api.h"

static napi_value init(napi_env env, napi_value exports)
{
    napi_property_descriptor descs[] = {
        {"version", 0, version, 0, 0, 0, napi_default, 0},
        {"ctxNew", 0, ctx_new, 0, 0, 0, napi_default, 0},
        {"ctxShutdown", 0, ctx_shutdown, 0, 0, 0, napi_default, 0},
        {"ctxTerm", 0, ctx_term, 0, 0, 0, napi_default, 0},
        {"ctxSetOpt", 0, ctx_setopt, 0, 0, 0, napi_default, 0},
        {"ctxGetOpt", 0, ctx_getopt, 0, 0, 0, napi_default, 0},
        {"socketNew", 0, socket_new, 0, 0, 0, napi_default, 0},
        {"socketClose", 0, socket_close, 0, 0, 0, napi_default, 0},
        {"socketBind", 0, socket_bind, 0, 0, 0, napi_default, 0},
        {"socketUnbind", 0, socket_unbind, 0, 0, 0, napi_default, 0},
        {"socketConnect", 0, socket_connect, 0, 0, 0, napi_default, 0},
        {"socketDisconnect", 0, socket_disconnect, 0, 0, 0, napi_default, 0},
        {"socketDisconnectRid", 0, socket_disconnect_rid, 0, 0, 0, napi_default, 0},
        {"socketSetTlsServer", 0, socket_set_tls_server, 0, 0, 0, napi_default, 0},
        {"socketSetTlsClient", 0, socket_set_tls_client, 0, 0, 0, napi_default, 0},
        {"socketAttachDiscovery", 0, socket_attach_discovery, 0, 0, 0, napi_default, 0},
        {"socketSend", 0, socket_send, 0, 0, 0, napi_default, 0},
        {"socketSendParts", 0, socket_send_parts, 0, 0, 0, napi_default, 0},
        {"socketPublish", 0, socket_publish, 0, 0, 0, napi_default, 0},
        {"socketTryPublish", 0, socket_try_publish, 0, 0, 0, napi_default, 0},
        {"socketSendNoWaitResult", 0, socket_try_send, 0, 0, 0, napi_default, 0},
        {"socketSendNoWaitResultParts", 0, socket_try_send_parts, 0, 0, 0, napi_default, 0},
        {"socketSendRoutingNoWaitResult", 0, socket_try_send_routing, 0, 0, 0, napi_default, 0},
        {"socketSendRoutingNoWaitResultParts", 0, socket_try_send_routing_parts, 0, 0, 0, napi_default, 0},
        {"socketSendFrom", 0, socket_send_from, 0, 0, 0, napi_default, 0},
        {"socketRecv", 0, socket_recv, 0, 0, 0, napi_default, 0},
        {"socketRecvMessage", 0, socket_recv_message, 0, 0, 0, napi_default, 0},
        {"socketRecvMessageNoWait", 0, socket_try_recv_message, 0, 0, 0, napi_default, 0},
        {"socketRecvHandler", 0, socket_recv_handler, 0, 0, 0, napi_default, 0},
        {"socketSubscribeMessage", 0, socket_subscribe_message, 0, 0, 0, napi_default, 0},
        {"socketTrySubscribeMessage", 0, socket_try_subscribe_message, 0, 0, 0, napi_default, 0},
        {"socketSubscribeHandler", 0, socket_subscribe_handler, 0, 0, 0, napi_default, 0},
        {"socketSendReadyHandler", 0, socket_send_ready_handler, 0, 0, 0, napi_default, 0},
        {"socketSubscriptionEvent", 0, socket_subscription_event, 0, 0, 0, napi_default, 0},
        {"socketTrySubscriptionEvent", 0, socket_try_subscription_event, 0, 0, 0, napi_default, 0},
        {"socketRecvInto", 0, socket_recv_into, 0, 0, 0, napi_default, 0},
        {"socketRecvMsgInto", 0, socket_recv_msg_into, 0, 0, 0, napi_default, 0},
        {"socketStreamAttach", 0, socket_stream_attach, 0, 0, 0, napi_default, 0},
        {"socketStreamDetach", 0, socket_stream_detach, 0, 0, 0, napi_default, 0},
        {"socketStreamPeerRoutingId", 0, socket_stream_peer_routing_id, 0, 0, 0, napi_default, 0},
        {"socketStreamSend", 0, socket_stream_send, 0, 0, 0, napi_default, 0},
        {"socketSetOpt", 0, socket_setopt, 0, 0, 0, napi_default, 0},
        {"socketGetOpt", 0, socket_getopt, 0, 0, 0, napi_default, 0},
        {"socketSetChannelName", 0, socket_set_channel_name, 0, 0, 0, napi_default, 0},
        {"socketGetChannelName", 0, socket_get_channel_name, 0, 0, 0, napi_default, 0},
        {"handleSetRoutingId", 0, handle_set_routing_id, 0, 0, 0, napi_default, 0},
        {"handleGetRoutingId", 0, handle_get_routing_id, 0, 0, 0, napi_default, 0},
        {"dealerRequest", 0, dealer_request, 0, 0, 0, napi_default, 0},
        {"socketRequestProgress", 0, socket_request_progress, 0, 0, 0,
         napi_default, 0},
        {"routerRequest", 0, router_request, 0, 0, 0, napi_default, 0},
        {"routerReply", 0, router_reply, 0, 0, 0, napi_default, 0},
        {"routerHandlerMessage", 0, router_handler_message, 0, 0, 0, napi_default, 0},
        {"routerRecvMessage", 0, router_recv_message, 0, 0, 0, napi_default, 0},
        {"routerRecvMessageNoWait", 0, router_try_recv_message, 0, 0, 0, napi_default, 0},
        {"routerSpotSend", 0, router_spot_send, 0, 0, 0, napi_default, 0},
        {"routerSpotRequest", 0, router_spot_request, 0, 0, 0, napi_default, 0},
        {"routerSpotReply", 0, router_spot_reply, 0, 0, 0, napi_default, 0},

        {"registryNew", 0, registry_new, 0, 0, 0, napi_default, 0},
        {"registrySetEndpoints", 0, registry_set_endpoints, 0, 0, 0, napi_default, 0},
        {"registrySetId", 0, registry_set_id, 0, 0, 0, napi_default, 0},
        {"registryAddPeer", 0, registry_add_peer, 0, 0, 0, napi_default, 0},
        {"registrySetHeartbeat", 0, registry_set_heartbeat, 0, 0, 0, napi_default, 0},
        {"registrySetBroadcastInterval", 0, registry_set_broadcast, 0, 0, 0, napi_default, 0},
        {"registrySetTlsServer", 0, registry_set_tls_server, 0, 0, 0, napi_default, 0},
        {"registrySetTlsClient", 0, registry_set_tls_client, 0, 0, 0, napi_default, 0},
        {"registryStart", 0, registry_start, 0, 0, 0, napi_default, 0},
        {"registrySetSockOpt", 0, registry_setsockopt, 0, 0, 0, napi_default, 0},
        {"registryStatusSnapshot", 0, registry_status_snapshot, 0, 0, 0, napi_default, 0},
        {"registryServiceSummarySnapshot", 0, registry_service_summary_snapshot, 0, 0, 0, napi_default, 0},
        {"registryTopologySnapshot", 0, registry_topology_snapshot, 0, 0, 0, napi_default, 0},
        {"registryTopologyQuery", 0, registry_topology_query, 0, 0, 0, napi_default, 0},
        {"registryMemberPeers", 0, registry_member_peers, 0, 0, 0, napi_default, 0},
        {"registryMemberPeerMetadata", 0, registry_member_peer_metadata, 0, 0, 0, napi_default, 0},
        {"registryQueryClientNew", 0, registry_query_client_new, 0, 0, 0, napi_default, 0},
        {"registryQueryClientConnect", 0, registry_query_client_connect, 0, 0, 0, napi_default, 0},
        {"registryQuerySnapshot", 0, registry_query_snapshot, 0, 0, 0, napi_default, 0},
        {"registryQueryDestroy", 0, registry_query_destroy, 0, 0, 0, napi_default, 0},
        {"registryDestroy", 0, registry_destroy, 0, 0, 0, napi_default, 0},

        {"discoveryNew", 0, discovery_new, 0, 0, 0, napi_default, 0},
        {"discoveryConnectRegistry", 0, discovery_connect, 0, 0, 0, napi_default, 0},
        {"discoveryProviderCount", 0, discovery_provider_count, 0, 0, 0, napi_default, 0},
        {"discoveryServiceAvailable", 0, discovery_service_available, 0, 0, 0, napi_default, 0},
        {"discoveryGetProviders", 0, discovery_get_providers, 0, 0, 0, napi_default, 0},
        {"discoveryMemberPeerMetadata", 0, discovery_member_peer_metadata, 0, 0, 0, napi_default, 0},
        {"discoverySetValue", 0, discovery_set_value, 0, 0, 0, napi_default, 0},
        {"discoveryGetValue", 0, discovery_get_value, 0, 0, 0, napi_default, 0},
        {"discoverySetMetadata", 0, discovery_set_metadata, 0, 0, 0, napi_default, 0},
        {"discoveryGetMetadata", 0, discovery_get_metadata, 0, 0, 0, napi_default, 0},
        {"discoveryResolveSpot", 0, discovery_resolve_spot, 0, 0, 0, napi_default, 0},
        {"discoverySetDealerPeerMode", 0, discovery_set_dealer_peer_mode, 0, 0, 0, napi_default, 0},
        {"discoverySetTlsClient", 0, discovery_set_tls_client, 0, 0, 0, napi_default, 0},
        {"discoveryDestroy", 0, discovery_destroy, 0, 0, 0, napi_default, 0},

        {"providerNew", 0, provider_new, 0, 0, 0, napi_default, 0},
        {"providerBind", 0, provider_bind, 0, 0, 0, napi_default, 0},
        {"providerConnectRegistry", 0, provider_connect_registry, 0, 0, 0, napi_default, 0},
        {"providerRegister", 0, provider_register, 0, 0, 0, napi_default, 0},
        {"providerUpdateWeight", 0, provider_update_weight, 0, 0, 0, napi_default, 0},
        {"providerUnregister", 0, provider_unregister, 0, 0, 0, napi_default, 0},
        {"providerRegisterResult", 0, provider_register_result, 0, 0, 0, napi_default, 0},
        {"providerSetTlsServer", 0, provider_set_tls_server, 0, 0, 0, napi_default, 0},
        {"providerRouter", 0, provider_router, 0, 0, 0, napi_default, 0},
        {"providerRouterPeers", 0, provider_router_peers, 0, 0, 0, napi_default, 0},
        {"providerSetSockOpt", 0, provider_setsockopt, 0, 0, 0, napi_default, 0},
        {"providerDestroy", 0, provider_destroy, 0, 0, 0, napi_default, 0},

        {"spotNodeNew", 0, spot_node_new, 0, 0, 0, napi_default, 0},
        {"spotNodeDestroy", 0, spot_node_destroy, 0, 0, 0, napi_default, 0},
        {"spotNodeBind", 0, spot_node_bind, 0, 0, 0, napi_default, 0},
        {"spotNodeConnectPeerPub", 0, spot_node_connect_peer, 0, 0, 0, napi_default, 0},
        {"spotNodeDisconnectPeerPub", 0, spot_node_disconnect_peer, 0, 0, 0, napi_default, 0},
        {"spotNodeDisconnectPeerRidPub", 0, spot_node_disconnect_peer_rid, 0, 0, 0, napi_default, 0},
        {"spotNodeRegister", 0, spot_node_register, 0, 0, 0, napi_default, 0},
        {"spotNodeUnregister", 0, spot_node_unregister, 0, 0, 0, napi_default, 0},
        {"spotNodeSetDiscovery", 0, spot_node_set_discovery, 0, 0, 0, napi_default, 0},
        {"spotNodeAttachChannelDealer", 0, spot_node_attach_channel_dealer, 0, 0, 0, napi_default, 0},
        {"spotNodeAttachChannelDealerManual", 0, spot_node_attach_channel_dealer_manual, 0, 0, 0, napi_default, 0},
        {"spotNodeAttachPubIngress", 0, spot_node_attach_pub_ingress, 0, 0, 0, napi_default, 0},
        {"spotNodeSetTlsServer", 0, spot_node_set_tls_server, 0, 0, 0, napi_default, 0},
        {"spotNodeSetTlsClient", 0, spot_node_set_tls_client, 0, 0, 0, napi_default, 0},
        {"spotNodeSetOption", 0, spot_node_setsockopt, 0, 0, 0, napi_default, 0},
        {"spotNodeStatusSnapshot", 0, spot_node_status_snapshot, 0, 0, 0, napi_default, 0},
        {"spotNodePeersSnapshot", 0, spot_node_peers_snapshot, 0, 0, 0, napi_default, 0},
        {"spotNodePeersQuery", 0, spot_node_peers_query, 0, 0, 0, napi_default, 0},
        {"spotNodeSubjectsSnapshot", 0, spot_node_subjects_snapshot, 0, 0, 0, napi_default, 0},
        {"spotNodeInternalSocketsSnapshot", 0, spot_node_internal_sockets_snapshot, 0, 0, 0, napi_default, 0},
        {"spotNodePubSocket", 0, spot_node_pub_socket, 0, 0, 0, napi_default, 0},
        {"spotNodeSubSocket", 0, spot_node_sub_socket, 0, 0, 0, napi_default, 0},
        {"spotNodePubPeers", 0, spot_node_pub_peers, 0, 0, 0, napi_default, 0},
        {"spotNodeSubPeers", 0, spot_node_sub_peers, 0, 0, 0, napi_default, 0},

        {"spotNew", 0, spot_new, 0, 0, 0, napi_default, 0},
        {"spotDestroy", 0, spot_destroy, 0, 0, 0, napi_default, 0},
        {"spotPublish", 0, spot_publish, 0, 0, 0, napi_default, 0},
        {"spotTryPublish", 0, spot_try_publish, 0, 0, 0, napi_default, 0},
        {"spotSendChannel", 0, spot_send_channel, 0, 0, 0, napi_default, 0},
        {"spotSendToSpot", 0, spot_send_spot, 0, 0, 0, napi_default, 0},
        {"spotRequestChannel", 0, spot_request_channel, 0, 0, 0, napi_default, 0},
        {"spotRequestProgress", 0, spot_request_progress, 0, 0, 0,
         napi_default, 0},
        {"spotChannelReplyProgress", 0, spot_channel_reply_progress, 0, 0, 0,
         napi_default, 0},
        {"spotReplySpot", 0, spot_reply_spot, 0, 0, 0, napi_default, 0},
        {"spotReplyRouter", 0, spot_reply_router, 0, 0, 0, napi_default, 0},
        {"spotRoutedHandler", 0, spot_routed_handler, 0, 0, 0, napi_default, 0},
        {"spotDispatchEventHandler", 0, spot_dispatch_event_handler, 0, 0, 0, napi_default, 0},
        {"spotRecvRouted", 0, spot_recv_routed, 0, 0, 0, napi_default, 0},
        {"spotSendReadyHandler", 0, spot_send_ready_handler, 0, 0, 0,
         napi_default, 0},
        {"spotSubscribe", 0, spot_subscribe, 0, 0, 0, napi_default, 0},
        {"spotSubscribePattern", 0, spot_subscribe_pattern, 0, 0, 0, napi_default, 0},
        {"spotUnsubscribe", 0, spot_unsubscribe, 0, 0, 0, napi_default, 0},
        {"spotRecv", 0, spot_recv, 0, 0, 0, napi_default, 0},
        {"spotRecvNoWait", 0, spot_try_recv, 0, 0, 0, napi_default, 0},
        {"spotSubscriptionEvent", 0, spot_subscription_event, 0, 0, 0, napi_default, 0},
        {"spotSubscriptionEventNoWait", 0, spot_try_subscription_event, 0, 0, 0, napi_default, 0},
        {"spotSubscribeHandler", 0, spot_subscribe_handler, 0, 0, 0, napi_default, 0},
        {"monitorOpen", 0, monitor_open, 0, 0, 0, napi_default, 0},
        {"monitorHandler", 0, monitor_handler, 0, 0, 0, napi_default, 0},
        {"monitorRecv", 0, monitor_recv, 0, 0, 0, napi_default, 0},
        {"monitorRecvNoWait", 0, monitor_try_recv, 0, 0, 0, napi_default, 0},
        {"monitorSnapshot", 0, monitor_snapshot, 0, 0, 0, napi_default, 0},
        {"monitorClose", 0, monitor_close, 0, 0, 0, napi_default, 0},

        {"pollerNew", 0, poller_new, 0, 0, 0, napi_default, 0},
        {"pollerDestroy", 0, poller_destroy, 0, 0, 0, napi_default, 0},
        {"pollerSize", 0, poller_size, 0, 0, 0, napi_default, 0},
        {"pollerAdd", 0, poller_add, 0, 0, 0, napi_default, 0},
        {"pollerModify", 0, poller_modify, 0, 0, 0, napi_default, 0},
        {"pollerRemove", 0, poller_remove, 0, 0, 0, napi_default, 0},
        {"pollerAddFd", 0, poller_add_fd, 0, 0, 0, napi_default, 0},
        {"pollerModifyFd", 0, poller_modify_fd, 0, 0, 0, napi_default, 0},
        {"pollerRemoveFd", 0, poller_remove_fd, 0, 0, 0, napi_default, 0},
        {"pollerAddTimer", 0, poller_add_timer, 0, 0, 0, napi_default, 0},
        {"pollerRemoveTimer", 0, poller_remove_timer, 0, 0, 0, napi_default, 0},
        {"pollerWait", 0, poller_wait, 0, 0, 0, napi_default, 0},
        {"pollerWaitAll", 0, poller_wait_all, 0, 0, 0, napi_default, 0},

        {"timerNew", 0, timer_new, 0, 0, 0, napi_default, 0},
        {"spotTimerNew", 0, spot_timer_new, 0, 0, 0, napi_default, 0},
        {"timerDestroy", 0, timer_destroy, 0, 0, 0, napi_default, 0},
        {"timerStart", 0, timer_start, 0, 0, 0, napi_default, 0},
        {"timerStop", 0, timer_stop, 0, 0, 0, napi_default, 0},
        {"timerRecv", 0, timer_recv, 0, 0, 0, napi_default, 0},
        {"timerHandler", 0, timer_handler, 0, 0, 0, napi_default, 0},

        {"stopwatchStart", 0, stopwatch_start, 0, 0, 0, napi_default, 0},
        {"stopwatchIntermediate", 0, stopwatch_intermediate, 0, 0, 0, napi_default, 0},
        {"stopwatchStop", 0, stopwatch_stop, 0, 0, 0, napi_default, 0},

        {"poll", 0, poll, 0, 0, 0, napi_default, 0},
    };

    napi_define_properties(env, exports, sizeof(descs) / sizeof(*descs), descs);
    return exports;
}

NAPI_MODULE(NODE_GYP_MODULE_NAME, init)
