<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>12.0</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <ProjectReference Include="..\Api\TicTacToe.SessionGateway.Api.csproj" />
    <ProjectReference Include="..\Client\TicTacToe.SessionGateway.Client.csproj" />
    <ProjectReference Include="..\Infrastructure\TicTacToe.SessionGateway.Infrastructure.csproj" />
    <ProjectReference Include="..\Play\TicTacToe.SessionGateway.Play.csproj" />
    <ProjectReference Include="..\Registry\TicTacToe.SessionGateway.Registry.csproj" />
    <ProjectReference Include="..\Session\TicTacToe.SessionGateway.Session.csproj" />
    <ProjectReference Include="..\Shared\TicTacToe.SessionGateway.Shared.csproj" />
    <ProjectReference Include="../../../src/Zlink.Framework/Zlink.Framework.csproj" />
  </ItemGroup>
</Project>
