<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../Direct/TicTacToe.Direct.csproj" />
    <ProjectReference Include="../../SessionGateway/TicTacToe.SessionGateway.csproj" />
  </ItemGroup>
</Project>
